version: binned_2016_v5

defaults:
  module_samples: "data.samples_RunII"
  default_binning:
    - ["tr_ttbar_mass", [300, 400, 500, 650, 1500]]
    - ["tr_ttbar_y", [-2.5, -1.2, -0.8, -0.4, 0.4, 0.8, 1.2, 2.5]]
        
likelihood:
    binned:
        - id: SR_2016 
          classes: 
            - id: TTLep_pow_2016 
              sample: TTLep_pow_2016
              POI:
                job: ich_NG_PDF4LHC21_1_TTLep_pow_2016 
                type: ich
                parameters: [c0]
              systematics:
                - id: Lumi
                  type: lnN
                  value: 0.05
                  parameters: [nu_lumi]              
                - id: L1Prefire
                  type: icph
                  job: icph_TTLep_pow_2016_L1Prefire
                  parameters: [nu_l1prefire]
                - id: PU
                  type: icph
                  job: icph_TTLep_pow_2016_PU
                  parameters: [nu_pu]
                - id: MuSF 
                  type: icph
                  job: icph_TTLep_pow_2016_MuSF
                  parameters: [nu_MuSF]
                - id: EleSF
                  type: icph
                  job: icph_TTLep_pow_2016_EleSF
                  parameters: [nu_EleSF]
                - id: BTag_b
                  type: icph
                  job: icph_TTLep_pow_2016_BTag_b
                  parameters: [nu_btag_b]
                - id: BTag_l
                  type: icph
                  job: icph_TTLep_pow_2016_BTag_l
                  parameters: [nu_btag_l]
                - id: Scales
                  type: icph
                  job: icph_TTLep_pow_2016_scales
                  parameters: [nu_mu_ren, nu_mu_fac]
                - id: ShowerISR
                  type: icph
                  job: icph_TTLep_pow_2016_showerISR
                  parameters: [nu_showerISR]
                - id: ShowerFSR
                  type: icph
                  job: icph_TTLep_pow_2016_showerFSR
                  parameters: [nu_showerFSR]
                - id: AlphaS
                  type: icph
                  job: icph_TTLep_pow_2016_alphaS
                  parameters: [nu_alphaS]
                - id: CMS_res_j_0
                  type: icph
                  job: icph_TTLep_pow_2016_CMS_res_j_0_2016
                  parameters: [nu_CMS_res_j_0]
                - id: CMS_res_j_1
                  type: icph
                  job: icph_TTLep_pow_2016_CMS_res_j_1_2016
                  parameters: [nu_CMS_res_j_1]
                - id: CMS_res_j_2
                  type: icph
                  job: icph_TTLep_pow_2016_CMS_res_j_2_2016
                  parameters: [nu_CMS_res_j_2]
                - id: CMS_res_j_3
                  type: icph
                  job: icph_TTLep_pow_2016_CMS_res_j_3_2016
                  parameters: [nu_CMS_res_j_3]
                - id: CMS_res_j_4
                  type: icph
                  job: icph_TTLep_pow_2016_CMS_res_j_4_2016
                  parameters: [nu_CMS_res_j_4]
                - id: CMS_res_j_5
                  type: icph
                  job: icph_TTLep_pow_2016_CMS_res_j_5_2016
                  parameters: [nu_CMS_res_j_5]
                - id: CMS_scale_j_Total_EtaBin0
                  type: icph
                  job: icph_TTLep_pow_2016_CMS_scale_j_Total_EtaBin0
                  parameters: [nu_CMS_scale_j_Total_EtaBin0]
                - id: CMS_scale_j_Total_EtaBin1
                  type: icph
                  job: icph_TTLep_pow_2016_CMS_scale_j_Total_EtaBin1
                  parameters: [nu_CMS_scale_j_Total_EtaBin1]
                - id: CMS_scale_j_Total_EtaBin2
                  type: icph
                  job: icph_TTLep_pow_2016_CMS_scale_j_Total_EtaBin2
                  parameters: [nu_CMS_scale_j_Total_EtaBin2]
                - id: CMS_scale_j_Total_EtaBin3
                  type: icph
                  job: icph_TTLep_pow_2016_CMS_scale_j_Total_EtaBin3
                  parameters: [nu_CMS_scale_j_Total_EtaBin3]
                - id: CMS_scale_j_Total_EtaBin4
                  type: icph
                  job: icph_TTLep_pow_2016_CMS_scale_j_Total_EtaBin4
                  parameters: [nu_CMS_scale_j_Total_EtaBin4]
                - id: CMS_scale_j_Total_EtaBin5
                  type: icph
                  job: icph_TTLep_pow_2016_CMS_scale_j_Total_EtaBin5
                  parameters: [nu_CMS_scale_j_Total_EtaBin5]
                - id: Uncl
                  type: icph
                  job: icph_TTLep_pow_2016_Uncl
                  parameters: [nu_Uncl]

jobs:
  - id: ich_NG_PDF4LHC21_1_TTLep_pow_2016 
    type: ich
    region: SR_binned
    process: TTLep_pow_2016
    pdf:
      #pdf_n: [1, 2, 4, 5, 10, 12]
      #pdf_type: PODBasis
      pdf_n: [1]
      pdf_type: PODBasis
      pdf_basis: gluon_POD_nongluon_PDF4LHC21 

  - id: icph_TTLep_pow_2016_L1Prefire
    type: icph
    region: SR_binned
    parameters: [nu_l1prefire]
    combinations: [[nu_l1prefire]]
    base_points:
      - coords: [-1.0]
        loader: TTLep_pow_2016
        removeweights: ["L1PreFiringWeight_Nom"] 
        addweights: ["L1PreFiringWeight_Dn"] 
      - coords: [ 0.0]
        loader: TTLep_pow_2016
        nominal: true
      - coords: [ 1.0]
        loader: TTLep_pow_2016
        removeweights: ["L1PreFiringWeight_Nom"] 
        addweights: ["L1PreFiringWeight_Up"] 
  
  - id: icph_TTLep_pow_2016_PU
    type: icph
    region: SR_binned
    parameters: [nu_pu]
    combinations: [[nu_pu]]
    base_points:
      - coords: [-1.0]
        loader: TTLep_pow_2016
        removeweights: ["Pileup_SF"] 
        addweights: ["Pileup_SFDn"] 
      - coords: [ 0.0]
        loader: TTLep_pow_2016
        nominal: true
      - coords: [ 1.0]
        loader: TTLep_pow_2016
        removeweights: ["Pileup_SF"] 
        addweights: ["Pileup_SFUp"] 

  - id: icph_TTLep_pow_2016_MuSF 
    type: icph
    region: SR_binned
    parameters: [nu_MuSF]
    combinations: [[nu_MuSF]]
    base_points:
      - coords: [-1.0]
        loader: TTLep_pow_2016
        removeweights: ["lepMu_SF"] 
        addweights: ["lepMu_SFDn"] 
      - coords: [ 0.0]
        loader: TTLep_pow_2016
        nominal: true
      - coords: [ 1.0]
        loader: TTLep_pow_2016
        removeweights: ["lepMu_SF"] 
        addweights: ["lepMu_SFUp"] 

  - id: icph_TTLep_pow_2016_EleSF 
    type: icph
    region: SR_binned
    parameters: [nu_EleSF]
    combinations: [[nu_EleSF]]
    base_points:
      - coords: [-1.0]
        loader: TTLep_pow_2016
        removeweights: ["lepEle_SF"] 
        addweights: ["lepEle_SFDn"] 
      - coords: [ 0.0]
        loader: TTLep_pow_2016
        nominal: true
      - coords: [ 1.0]
        loader: TTLep_pow_2016
        removeweights: ["lepEle_SF"] 
        addweights: ["lepEle_SFUp"] 
  
  - id: icph_TTLep_pow_2016_BTag_b
    type: icph
    region: SR_binned
    parameters: [nu_btag_b]
    combinations: [[nu_btag_b]]
    base_points:
      - coords: [-1.0]
        loader: TTLep_pow_2016
        removeweights: ["btagSF_fixedWP_SF"] 
        addweights: ["btagSF_fixedWP_SF__CMS_eff_b_correlated_heavy_SFDn"] 
      - coords: [ 0.0]
        loader: TTLep_pow_2016
        nominal: true
      - coords: [ 1.0]
        loader: TTLep_pow_2016
        removeweights: ["btagSF_fixedWP_SF"] 
        addweights: ["btagSF_fixedWP_SF__CMS_eff_b_correlated_heavy_SFUp"] 
  
  - id: icph_TTLep_pow_2016_BTag_l
    type: icph
    region: SR_binned
    parameters: [nu_btag_l]
    combinations: [[nu_btag_l]]
    base_points:
      - coords: [-1.0]
        loader: TTLep_pow_2016
        removeweights: ["btagSF_fixedWP_SF"] 
        addweights: ["btagSF_fixedWP_SF__CMS_eff_b_light_SFDn"] 
      - coords: [ 0.0]
        loader: TTLep_pow_2016
        nominal: true
      - coords: [ 1.0]
        loader: TTLep_pow_2016
        removeweights: ["btagSF_fixedWP_SF"] 
        addweights: ["btagSF_fixedWP_SF__CMS_eff_b_light_SFUp"] 

  - id: icph_TTLep_pow_2016_scales
    type: icph
    region: SR_binned
    parameters: [nu_mu_ren, nu_mu_fac]
    combinations: [[nu_mu_ren], [nu_mu_fac], [nu_mu_ren, nu_mu_ren], [nu_mu_ren, nu_mu_fac], [nu_mu_fac, nu_mu_fac]]
    base_points:
      - coords: [-1.0, -1.0]
        loader: TTLep_pow_2016
        addweights: ["scale_ren0p5_fac0p5"]
      - coords: [-1.0, 0]
        loader: TTLep_pow_2016
        addweights: ["scale_ren0p5_fac1p0"]
      - coords: [-1.0, 1.0]
        loader: TTLep_pow_2016
        addweights: ["scale_ren0p5_fac2p0"]
      - coords: [0, -1.0]
        loader: TTLep_pow_2016
        addweights: ["scale_ren1p0_fac0p5"]
      - coords: [0, 0]
        loader: TTLep_pow_2016
        addweights: ["scale_ren1p0_fac1p0"]
        nominal: true
      - coords: [0, 1.0]
        loader: TTLep_pow_2016
        addweights: ["scale_ren1p0_fac2p0"]
      - coords: [1.0, -1.0]
        loader: TTLep_pow_2016
        addweights: ["scale_ren2p0_fac0p5"]
      - coords: [1.0, 0]
        loader: TTLep_pow_2016
        addweights: ["scale_ren2p0_fac1p0"]
      - coords: [1.0, 1.0]
        loader: TTLep_pow_2016
        addweights: ["scale_ren2p0_fac2p0"]

  - id: icph_TTLep_pow_2016_showerISR
    type: icph
    region: SR_binned
    parameters: [nu_showerISR]
    combinations: [[nu_showerISR]]
    base_points:
      - coords: [-1.0]
        loader: TTLep_pow_2016
        addweights: ["shower_isr0p5_fsr1p0"]
      - coords: [0]
        loader: TTLep_pow_2016
        nominal: true
      - coords: [1.0]
        loader: TTLep_pow_2016
        addweights: ["shower_isr2p0_fsr1p0"]

  - id: icph_TTLep_pow_2016_showerFSR
    type: icph
    region: SR_binned
    parameters: [nu_showerFSR]
    combinations: [[nu_showerFSR]]
    base_points:
      - coords: [-1.0]
        loader: TTLep_pow_2016
        addweights: ["shower_isr1p0_fsr0p5"]
      - coords: [0]
        loader: TTLep_pow_2016
        nominal: true
      - coords: [1.0]
        loader: TTLep_pow_2016
        addweights: ["shower_isr1p0_fsr2p0"]

  - id: icph_TTLep_pow_2016_alphaS
    type: icph
    region: SR_binned
    parameters: [nu_alphaS]
    combinations: [[nu_alphaS]]
    base_points:
      - coords: [-1.0]
        loader: TTLep_pow_2016
        addweights: ["pdf_alphas_dn"]
      - coords: [0]
        loader: TTLep_pow_2016
        nominal: true
      - coords: [1.0]
        loader: TTLep_pow_2016
        addweights: ["pdf_alphas_up"]

  - id: icph_TTLep_pow_2016_CMS_res_j_0_2016 
    type: icph
    region: SR_binned
    parameters: [nu_CMS_res_j_0]
    combinations: [[nu_CMS_res_j_0]]
    base_points:
      - coords: [-1.0]
        loader: TTLep_pow_2016_CMS_res_j_0_2016_down 
      - coords: [0]
        loader: TTLep_pow_2016
        nominal: true
      - coords: [1.0]
        loader: TTLep_pow_2016_CMS_res_j_0_2016_up

  - id: icph_TTLep_pow_2016_CMS_res_j_1_2016 
    type: icph
    region: SR_binned
    parameters: [nu_CMS_res_j_1]
    combinations: [[nu_CMS_res_j_1]]
    base_points:
      - coords: [-1.0]
        loader: TTLep_pow_2016_CMS_res_j_1_2016_down 
      - coords: [0]
        loader: TTLep_pow_2016
        nominal: true
      - coords: [1.0]
        loader: TTLep_pow_2016_CMS_res_j_1_2016_up

  - id: icph_TTLep_pow_2016_CMS_res_j_2_2016 
    type: icph
    region: SR_binned
    parameters: [nu_CMS_res_j_2]
    combinations: [[nu_CMS_res_j_2]]
    base_points:
      - coords: [-1.0]
        loader: TTLep_pow_2016_CMS_res_j_2_2016_down 
      - coords: [0]
        loader: TTLep_pow_2016
        nominal: true
      - coords: [1.0]
        loader: TTLep_pow_2016_CMS_res_j_2_2016_up

  - id: icph_TTLep_pow_2016_CMS_res_j_3_2016 
    type: icph
    region: SR_binned
    parameters: [nu_CMS_res_j_3]
    combinations: [[nu_CMS_res_j_3]]
    base_points:
      - coords: [-1.0]
        loader: TTLep_pow_2016_CMS_res_j_3_2016_down 
      - coords: [0]
        loader: TTLep_pow_2016
        nominal: true
      - coords: [1.0]
        loader: TTLep_pow_2016_CMS_res_j_3_2016_up

  - id: icph_TTLep_pow_2016_CMS_res_j_4_2016 
    type: icph
    region: SR_binned
    parameters: [nu_CMS_res_j_4]
    combinations: [[nu_CMS_res_j_4]]
    base_points:
      - coords: [-1.0]
        loader: TTLep_pow_2016_CMS_res_j_4_2016_down 
      - coords: [0]
        loader: TTLep_pow_2016
        nominal: true
      - coords: [1.0]
        loader: TTLep_pow_2016_CMS_res_j_4_2016_up

  - id: icph_TTLep_pow_2016_CMS_res_j_5_2016 
    type: icph
    region: SR_binned
    parameters: [nu_CMS_res_j_5]
    combinations: [[nu_CMS_res_j_5]]
    base_points:
      - coords: [-1.0]
        loader: TTLep_pow_2016_CMS_res_j_5_2016_down 
      - coords: [0]
        loader: TTLep_pow_2016
        nominal: true
      - coords: [1.0]
        loader: TTLep_pow_2016_CMS_res_j_5_2016_up

  # JES Eta-split bin 0
  - id: icph_TTLep_pow_2016_CMS_scale_j_Total_EtaBin0
    type: icph
    region: SR_binned
    parameters: [nu_CMS_scale_j_Total_EtaBin0]
    combinations: [[nu_CMS_scale_j_Total_EtaBin0]]
    base_points:
    - coords: [-1.0]
      loader: TTLep_pow_2016_CMS_scale_j_Total_EtaBin0_down
    - coords: [0]
      loader: TTLep_pow_2016
      nominal: true
    - coords: [1.0]
      loader: TTLep_pow_2016_CMS_scale_j_Total_EtaBin0_up

  # JES Eta-split bin 1
  - id: icph_TTLep_pow_2016_CMS_scale_j_Total_EtaBin1
    type: icph
    region: SR_binned
    parameters: [nu_CMS_scale_j_Total_EtaBin1]
    combinations: [[nu_CMS_scale_j_Total_EtaBin1]]
    base_points:
    - coords: [-1.0]
      loader: TTLep_pow_2016_CMS_scale_j_Total_EtaBin1_down
    - coords: [0]
      loader: TTLep_pow_2016
      nominal: true
    - coords: [1.0]
      loader: TTLep_pow_2016_CMS_scale_j_Total_EtaBin1_up

  # JES Eta-split bin 2
  - id: icph_TTLep_pow_2016_CMS_scale_j_Total_EtaBin2
    type: icph
    region: SR_binned
    parameters: [nu_CMS_scale_j_Total_EtaBin2]
    combinations: [[nu_CMS_scale_j_Total_EtaBin2]]
    base_points:
    - coords: [-1.0]
      loader: TTLep_pow_2016_CMS_scale_j_Total_EtaBin2_down
    - coords: [0]
      loader: TTLep_pow_2016
      nominal: true
    - coords: [1.0]
      loader: TTLep_pow_2016_CMS_scale_j_Total_EtaBin2_up

  # JES Eta-split bin 3
  - id: icph_TTLep_pow_2016_CMS_scale_j_Total_EtaBin3
    type: icph
    region: SR_binned
    parameters: [nu_CMS_scale_j_Total_EtaBin3]
    combinations: [[nu_CMS_scale_j_Total_EtaBin3]]
    base_points:
    - coords: [-1.0]
      loader: TTLep_pow_2016_CMS_scale_j_Total_EtaBin3_down
    - coords: [0]
      loader: TTLep_pow_2016
      nominal: true
    - coords: [1.0]
      loader: TTLep_pow_2016_CMS_scale_j_Total_EtaBin3_up

  # JES Eta-split bin 4
  - id: icph_TTLep_pow_2016_CMS_scale_j_Total_EtaBin4
    type: icph
    region: SR_binned
    parameters: [nu_CMS_scale_j_Total_EtaBin4]
    combinations: [[nu_CMS_scale_j_Total_EtaBin4]]
    base_points:
    - coords: [-1.0]
      loader: TTLep_pow_2016_CMS_scale_j_Total_EtaBin4_down
    - coords: [0]
      loader: TTLep_pow_2016
      nominal: true
    - coords: [1.0]
      loader: TTLep_pow_2016_CMS_scale_j_Total_EtaBin4_up

  # JES Eta-split bin 5
  - id: icph_TTLep_pow_2016_CMS_scale_j_Total_EtaBin5
    type: icph
    region: SR_binned
    parameters: [nu_CMS_scale_j_Total_EtaBin5]
    combinations: [[nu_CMS_scale_j_Total_EtaBin5]]
    base_points:
    - coords: [-1.0]
      loader: TTLep_pow_2016_CMS_scale_j_Total_EtaBin5_down
    - coords: [0]
      loader: TTLep_pow_2016
      nominal: true
    - coords: [1.0]
      loader: TTLep_pow_2016_CMS_scale_j_Total_EtaBin5_up

  - id: icph_TTLep_pow_2016_Uncl 
    type: icph
    region: SR_binned
    parameters: [nu_Uncl]
    combinations: [[nu_Uncl]]
    base_points:
      - coords: [-1.0]
        loader: TTLep_pow_2016_Uncl_down 
      - coords: [0]
        loader: TTLep_pow_2016
        nominal: true
      - coords: [1.0]
        loader: TTLep_pow_2016_Uncl_up

