python pnn_training.py ../../configs/merged_no_reg.yaml --overwrite  --job pnn_tt2l_Trigger
python pnn_training.py ../../configs/merged_no_reg.yaml --overwrite  --job pnn_tt2l_L1Prefire
python pnn_training.py ../../configs/merged_no_reg.yaml --overwrite  --job pnn_tt2l_PU
python pnn_training.py ../../configs/merged_no_reg.yaml --overwrite  --job pnn_tt2l_LeptonSF
python pnn_training.py ../../configs/merged_no_reg.yaml --overwrite  --job pnn_tt2l_BTag_b
python pnn_training.py ../../configs/merged_no_reg.yaml --overwrite  --job pnn_tt2l_BTag_l
python pnn_training.py ../../configs/merged_no_reg.yaml --overwrite  --job pnn_tt2l_scales

python pnn_training.py ../../configs/split_no_reg.yaml  --overwrite --job pnn_tt2l_GG_Trigger
python pnn_training.py ../../configs/split_no_reg.yaml  --overwrite --job pnn_tt2l_GG_L1Prefire
python pnn_training.py ../../configs/split_no_reg.yaml  --overwrite --job pnn_tt2l_GG_PU
python pnn_training.py ../../configs/split_no_reg.yaml  --overwrite --job pnn_tt2l_GG_LeptonSF
python pnn_training.py ../../configs/split_no_reg.yaml  --overwrite --job pnn_tt2l_GG_BTag_b
python pnn_training.py ../../configs/split_no_reg.yaml  --overwrite --job pnn_tt2l_GG_BTag_l
python pnn_training.py ../../configs/split_no_reg.yaml  --overwrite --job pnn_tt2l_GG_scales
python pnn_training.py ../../configs/split_no_reg.yaml  --overwrite --job pnn_tt2l_QG_Trigger
python pnn_training.py ../../configs/split_no_reg.yaml  --overwrite --job pnn_tt2l_QG_L1Prefire
python pnn_training.py ../../configs/split_no_reg.yaml  --overwrite --job pnn_tt2l_QG_PU
python pnn_training.py ../../configs/split_no_reg.yaml  --overwrite --job pnn_tt2l_QG_LeptonSF
python pnn_training.py ../../configs/split_no_reg.yaml  --overwrite --job pnn_tt2l_QG_BTag_b
python pnn_training.py ../../configs/split_no_reg.yaml  --overwrite --job pnn_tt2l_QG_BTag_l
python pnn_training.py ../../configs/split_no_reg.yaml  --overwrite --job pnn_tt2l_QG_scales
python pnn_training.py ../../configs/split_no_reg.yaml  --overwrite --job pnn_tt2l_QQ_Trigger
python pnn_training.py ../../configs/split_no_reg.yaml  --overwrite --job pnn_tt2l_QQ_L1Prefire
python pnn_training.py ../../configs/split_no_reg.yaml  --overwrite --job pnn_tt2l_QQ_PU
python pnn_training.py ../../configs/split_no_reg.yaml  --overwrite --job pnn_tt2l_QQ_LeptonSF
python pnn_training.py ../../configs/split_no_reg.yaml  --overwrite --job pnn_tt2l_QQ_BTag_b
python pnn_training.py ../../configs/split_no_reg.yaml  --overwrite --job pnn_tt2l_QQ_BTag_l
python pnn_training.py ../../configs/split_no_reg.yaml  --overwrite --job pnn_tt2l_QQ_scales
