python roc.py --small --filename tfmc_2_reg_lowMT_VBFJet              --selection lowMT_VBFJet              --modelDir /groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/lowMT_VBFJet/tfmc_2_reg/v6
python roc.py --small --filename tfmc_2_reg_highMT_VBFJet             --selection highMT_VBFJet             --modelDir /groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/highMT_VBFJet/tfmc_2_reg/v6
python roc.py --small --filename tfmc_2_reg_highMT_noVBFJet_ptH0to100 --selection highMT_noVBFJet_ptH0to100 --modelDir /groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/highMT_noVBFJet_ptH0to100/tfmc_2_reg/v6
python roc.py --small --filename tfmc_2_reg_highMT_noVBFJet_ptH100    --selection highMT_noVBFJet_ptH100    --modelDir /groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/highMT_noVBFJet_ptH100/tfmc_2_reg/v6
#python roc.py --small --filename tfmc_2_reg_lowMT_noVBFJet_ptH0to100  --selection lowMT_noVBFJet_ptH0to100  --modelDir /groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/lowMT_noVBFJet_ptH0to100/tfmc_2_reg/v6
python roc.py --small --filename tfmc_2_reg_lowMT_noVBFJet_ptH100     --selection lowMT_noVBFJet_ptH100     --modelDir /groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/lowMT_noVBFJet_ptH100/tfmc_2_reg/v6


#python roc.py  --small --filename lowMT_VBFJet_tfmc_2_reg --modelDirs /groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/lowMT_VBFJet/tfmc_2_reg/v6
python roc.py --small --filename tfmc_postproc_lowMT_VBFJet  --selection lowMT_VBFJet              --modelDir /groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/lowMT_VBFJet/tfmc_postproc_lowMT_VBFJet/v6

python roc.py --small --filename tfmc_lowMT_VBFJet_postproc_comp  --selection lowMT_VBFJet --modelDirs /groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/lowMT_VBFJet/tfmc_2_reg_preproc/v6 /groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/lowMT_VBFJet/tfmc_postproc_lowMT_VBFJet/v6/ /groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/lowMT_VBFJet/tfmc_2_reg/v6
python roc.py --small --filename tfmc_highMT_VBFJet_postproc_comp  --selection highMT_VBFJet --modelDirs /groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/highMT_VBFJet/tfmc_2_reg_preproc/v6 /groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/highMT_VBFJet/tfmc_postproc_highMT_VBFJet/v6/ /groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/highMT_VBFJet/tfmc_2_reg/v6
python roc.py --small --filename tfmc_highMT_noVBFJet_postproc_comp  --selection highMT_noVBFJet --modelDirs /groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/highMT_noVBFJet/tfmc_2_reg_preproc/v6 /groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/highMT_noVBFJet/tfmc_postproc_highMT_noVBFJet/v6/ /groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/highMT_noVBFJet/tfmc_2_reg/v6
python roc.py --small --filename tfmc_lowMT_noVBFJet_ptH100_postproc_comp  --selection lowMT_noVBFJet_ptH100 --modelDirs /groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/lowMT_noVBFJet_ptH100/tfmc_2_reg_preproc/v6 /groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/lowMT_noVBFJet_ptH100/tfmc_postproc_lowMT_noVBFJet_ptH100/v6/ /groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/lowMT_noVBFJet_ptH100/tfmc_2_reg/v6
