Tasks:
  - MultiClassifier
  - JES

Data:
  selections:
    - "lowMT_VBFJet"
  n_split: 100
  max_n_batch: 1 # set to -1 as infinity
  Toy:
    dir: "/scratch-cbe/users/robert.schoefbeck/Higgs_uncertainty/data/"
    filename: "jes_0p99_met_2.h5"
    n_split: 100
    batch_size: 
  

Predict:
  sim_path: "test"

MultiClassifier:
  module: "TFMC"
  model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/lowMT_VBFJet/tfmc_5/v5"
  save:
    - predict

JES:
  module: "PNN"
  model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/PNN/lowMT_VBFJet/pnn_quad_jes/v3"
  save:
    - DeltaA

Parameters:
  alpha_bkg: 0.001
  alpha_tt: 0.02
  alpha_diboson: 0.25
