Tasks:
  - MultiClassifier
  - htautau
  - ztautau
  - ttbar
  - diboson

Data:
  selections:
    - "lowMT_VBFJet"
  n_split: 100
  max_n_batch: 1 # set to -1 as infinity
  Toy:
    dir: "/scratch-cbe/users/robert.schoefbeck/Higgs_uncertainty/data/"
    filename: "jes_0p99_met_2.h5"
    n_split: 100
    batch_size: 
  

Predict:
  sim_path: "test"
  use_toy: True

MultiClassifier:
  module: "TFMC"
  model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/lowMT_VBFJet/tfmc_2_reg/v6"
  save:
    - predict

htautau:
  module: "PNN"
  model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/PNN/htautau/lowMT_VBFJet/pnn_quad_tes_jes_met/v1"
  save:
    - DeltaA

ztautau:
  module: "PNN"
  model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/PNN/ztautau/lowMT_VBFJet/pnn_quad_tes_jes_met/v1"
  save:
    - DeltaA

ttbar:
  module: "PNN"
  model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/PNN/ttbar/lowMT_VBFJet/pnn_quad_tes_jes_met/v1"
  save:
    - DeltaA

diboson:
  module: "PNN"
  model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/PNN/diboson/lowMT_VBFJet/pnn_quad_tes_jes_met/v1"
  save:
    - DeltaA

Parameters:
  alpha_bkg: 0.001
  alpha_tt: 0.02
  alpha_diboson: 0.25
