Tasks:
  - MultiClassifier
  - htautau
  - ztautau
  - ttbar
  - diboson

Selections:
  #- "lowMT_VBFJet"
    #  - "lowMT_noVBFJet_ptH0to100"
  # "lowMT_noVBFJet_ptH100"
    #  - "highMT"
    #  - "highMT_noVBFJet"
      - "highMT_VBFJet"

Toy_name: "jes_0p99_met_2"

Save:
  TrainingData: # pre-defined "TrainingData" used for training
    n_split: 1
    max_n_batch: -1 # set to -1 as infinity

  Toy: # toys, name can be changed
    dir: "/scratch-cbe/users/robert.schoefbeck/Higgs_uncertainty/data/"
    filename: "jes_0p99_met_2.h5"
#    filename: "nominal.h5"
    n_split: 1
    batch_size: 
    max_n_batch: -1

# Cubic spline interpolation for inclusive cross section
CSI: True 

Predict:
  use_toy: True
  TrainingData: "TrainingData"

MultiClassifier:
  lowMT_VBFJet:
    module: "TFMC"
    model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/lowMT_VBFJet/tfmc_2_reg/v6"
  lowMT_noVBFJet_ptH0to100:
    module: "TFMC"
    model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/lowMT_noVBFJet_ptH0to100/tfmc_2_reg/v6"
  lowMT_noVBFJet_ptH100:
    module: "TFMC"
    model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/lowMT_noVBFJet_ptH100/tfmc_2_reg/v6"
  highMT:
    module: "TFMC"
    model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/highMT/tfmc_5/v6"
  highMT_noVBFJet:
    module: "TFMC"
    model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/highMT_noVBFJet/tfmc_2_reg/v6"
  highMT_VBFJet:
    module: "TFMC"
    model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/TFMC/highMT_VBFJet/tfmc_2_reg/v6"
  save:
    - predict

htautau:
  lowMT_VBFJet:
    module: "PNN"
    model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/PNN/htautau/lowMT_VBFJet/pnn_quad_tes_jes_met/v1"
  lowMT_noVBFJet_ptH0to100:
    module: "PNN"
    model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/PNN/htautau/lowMT_noVBFJet_ptH0to100/pnn_quad_tes_jes_met/v1"
  lowMT_noVBFJet_ptH100:
    module: "PNN"
    model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/PNN/htautau/lowMT_noVBFJet_ptH100/pnn_quad_tes_jes_met/v1"
  highMT:
    module: "PNN"
    model_path: ""
  highMT_noVBFJet:
    module: "PNN"
    model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/PNN/htautau/highMT_noVBFJet/pnn_quad_tes_jes_met/v1"
  highMT_VBFJet:
    module: "PNN"
    model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/PNN/htautau/highMT_VBFJet/pnn_quad_tes_jes_met/v1"
  save:
    - DeltaA

ztautau:
  lowMT_VBFJet:
    module: "PNN"
    model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/PNN/ztautau/lowMT_VBFJet/pnn_quad_tes_jes_met/v1"
  lowMT_noVBFJet_ptH0to100:
    module: "PNN"
    model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/PNN/ztautau/lowMT_noVBFJet_ptH0to100/pnn_quad_tes_jes_met/v1"
  lowMT_noVBFJet_ptH100:
    module: "PNN"
    model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/PNN/ztautau/lowMT_noVBFJet_ptH100/pnn_quad_tes_jes_met/v1"
  highMT:
    module: "PNN"
    model_path: ""
  highMT_noVBFJet:
    module: "PNN"
    model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/PNN/ztautau/highMT_noVBFJet/pnn_quad_tes_jes_met/v1"
  highMT_VBFJet:
    module: "PNN"
    model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/PNN/htautau/highMT_VBFJet/pnn_quad_tes_jes_met/v1" #FIXME
  save:
    - DeltaA

ttbar:
  lowMT_VBFJet:
    module: "PNN"
    model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/PNN/ttbar/lowMT_VBFJet/pnn_quad_tes_jes_met/v1"
  lowMT_noVBFJet_ptH0to100:
    module: "PNN"
    model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/PNN/ttbar/lowMT_noVBFJet_ptH0to100/pnn_quad_tes_jes_met/v1"
  lowMT_noVBFJet_ptH100:
    module: "PNN"
    model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/PNN/ttbar/lowMT_noVBFJet_ptH100/pnn_lin_tes_jes_met/v1"
  highMT:
    module: "PNN"
    model_path: ""
  highMT_noVBFJet:
    module: "PNN"
    model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/PNN/ttbar/highMT_noVBFJet/pnn_quad_tes_jes_met/v1"
  highMT_VBFJet:
    module: "PNN"
    model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/PNN/ttbar/highMT_VBFJet/pnn_quad_tes_jes_met/v1"
  save:
    - DeltaA

diboson:
  lowMT_VBFJet:
    module: "PNN"
    model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/PNN/htautau/lowMT_VBFJet/pnn_quad_tes_jes_met/v1"
  lowMT_noVBFJet_ptH0to100:
    module: "PNN"
    model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/PNN/htautau/lowMT_noVBFJet_ptH0to100/pnn_quad_tes_jes_met/v1"
  lowMT_noVBFJet_ptH100:
    module: "PNN"
    model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/PNN/htautau/lowMT_noVBFJet_ptH100/pnn_quad_tes_jes_met/v1"
  highMT:
    module: "PNN"
    model_path: ""
  highMT_noVBFJet:
    module: "PNN"
    model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/PNN/htautau/highMT_noVBFJet/pnn_quad_tes_jes_met/v1"
  highMT_VBFJet:
    module: "PNN"
    model_path: "/groups/hephy/cms/robert.schoefbeck/Challenge/models/PNN/htautau/highMT_VBFJet/pnn_quad_tes_jes_met/v1"
  save:
    - DeltaA

Parameters:
  alpha_bkg: 0.001
  alpha_tt: 0.02
  alpha_diboson: 0.25
