Tasks:
#  - Classifier
  - ICP
#  - BPT
#  - Uncert_JES
#  - Fit

Classifier:
  module: "Model"
  model: "/path/to/model" # path of the trained ML model 
  input: "/path/to/input"
  output: "/path/to/output"
  hyper_param:
    nepochs: 100
    nlayers: 3

ICP:
  module: "ICP"
  model: "ICP_1203" # path of the trained ML model 
  input: "/path/to/input"
  output: "/path/to/output"
  config: "ML.configs.icp_quad_jes"
  selection: "lowMT_VBFJet"
  hyper_param:
    #nepochs: 100
    #nlayers: 3

BPT:
  module: "BoostedParametricTree"
  model: "/path/to/model" # path of the trained ML model 
  input: "/path/to/input"
  output: "/path/to/output"
  hyper_param:
    nepochs: 100
    nlayers: 3


Uncert_TES:
  module: "TES"
  model: "/path/to/model"
  input: "/path/to/input"
  output: "/path/to/output"
  hyper_param:
    nepochs: 100
    nlayers: 3

Fit:
  # Not clear yet what to put for this...
