version: unbinned_v3_eft_ND

defaults:
  module_samples: "data.samples_eft"
  default_features:
    - KINEMATICS

  splitting:
    enabled: true
    type: random
    seed: 0
    fraction: 0.5

  early_stopping:
    enabled: true
    patience: 20        # same as current hard-coded
    min_delta: 0.0      # improvement threshold; keep 0.0 to match current behavior
    mode: "min"         # val_loss should decrease
    warmup_epochs: 0    # optional: do not early-stop before this epoch


likelihood:
    regions:
        - id: SR 
          classifier:
            type: null
            id: null    # no classifier needed for a single process
            asimov: [TT01j2l_EFT_2016APV]
          classes: 
            - id: tt2l_gen
              sample: TT01j2l_EFT_2016APV 
              POI:
                job: bit_TT01j2l_EFT_2016APV 
                type: bit
                parameters: [ctGRe, ctGIm, cQd1]

jobs:
  - id: bit_TT01j2l_EFT_2016APV 
    type: bit
    region: SR
    process: TT01j2l_EFT_2016APV 
    selection: null               # optional extra selection layered on top
    numba: True
    eft:
        parameters: [ctGRe, ctGIm, cQd1]
    model:
      n_trees: 400
      learning_rate: 0.2
      loss: MSE                   # or "CrossEntropy"
      learn_global_score: true
      split_mode: "binned"
      n_bins: 256
      quantile_bins: true  # if True: quantile edges; else uniform edges
    runtime:
      training_plots: true        # keep if you want training plots
    output:
      filename: "bit_TT01j2l_EFT_2016APV.pkl"

  - id: bit_TT01j2l_EFT_2016
    type: bit
    region: SR
    process: TT01j2l_EFT_2016
    selection: null
    numba: True
    eft:
        parameters: [ctGRe, ctGIm, cQd1]
    model:
      n_trees: 400
      learning_rate: 0.2
      loss: MSE
      learn_global_score: true
      split_mode: "binned"
      n_bins: 256
      quantile_bins: true
    runtime:
      training_plots: true
    output:
      filename: "bit_TT01j2l_EFT_2016.pkl"

  - id: bit_TT01j2l_EFT_2017
    type: bit
    region: SR
    process: TT01j2l_EFT_2017
    selection: null
    numba: True
    eft:
        parameters: [ctGRe, ctGIm, cQd1]
    model:
      n_trees: 400
      learning_rate: 0.2
      loss: MSE
      learn_global_score: true
      split_mode: "binned"
      n_bins: 256
      quantile_bins: true
    runtime:
      training_plots: true
    output:
      filename: "bit_TT01j2l_EFT_2017.pkl"

  - id: bit_TT01j2l_EFT_2018
    type: bit
    region: SR
    process: TT01j2l_EFT_2018
    selection: null
    numba: True
    eft:
        parameters: [ctGRe, ctGIm, cQd1]
    model:
      n_trees: 400
      learning_rate: 0.2
      loss: MSE
      learn_global_score: true
      split_mode: "binned"
      n_bins: 256
      quantile_bins: true
    runtime:
      training_plots: true
    output:
      filename: "bit_TT01j2l_EFT_2018.pkl"

  - id: bit_TT01j2l_EFT_2016APV_allWC
    type: bit
    region: SR
    process: TT01j2l_EFT_2016APV
    selection: null
    numba: True
    eft:
        parameters: [cQd1, ctj1, cQj31, ctj8, ctd1, ctd8, ctGRe, ctGIm, cQj11, cQj18, ctu8, cQd8, ctu1, cQu1, cQj38, cQu8]
    model:
      n_trees: 400
      learning_rate: 0.2
      loss: MSE
      learn_global_score: true
      split_mode: "binned"
      n_bins: 256
      quantile_bins: true
    runtime:
      training_plots: true
    output:
      filename: "bit_TT01j2l_EFT_2016APV_allWC.pkl"

  - id: bit_TT01j2l_EFT_2016_allWC
    type: bit
    region: SR
    process: TT01j2l_EFT_2016
    selection: null
    numba: True
    eft:
        parameters: [cQd1, ctj1, cQj31, ctj8, ctd1, ctd8, ctGRe, ctGIm, cQj11, cQj18, ctu8, cQd8, ctu1, cQu1, cQj38, cQu8]
    model:
      n_trees: 400
      learning_rate: 0.2
      loss: MSE
      learn_global_score: true
      split_mode: "binned"
      n_bins: 256
      quantile_bins: true
    runtime:
      training_plots: true
    output:
      filename: "bit_TT01j2l_EFT_2016_allWC.pkl"

  - id: bit_TT01j2l_EFT_2017_allWC
    type: bit
    region: SR
    process: TT01j2l_EFT_2017
    selection: null
    numba: True
    eft:
        parameters: [cQd1, ctj1, cQj31, ctj8, ctd1, ctd8, ctGRe, ctGIm, cQj11, cQj18, ctu8, cQd8, ctu1, cQu1, cQj38, cQu8]
    model:
      n_trees: 400
      learning_rate: 0.2
      loss: MSE
      learn_global_score: true
      split_mode: "binned"
      n_bins: 256
      quantile_bins: true
    runtime:
      training_plots: true
    output:
      filename: "bit_TT01j2l_EFT_2017_allWC.pkl"

  - id: bit_TT01j2l_EFT_2018_allWC
    type: bit
    region: SR
    process: TT01j2l_EFT_2018
    selection: null
    numba: True
    eft:
        parameters: [cQd1, ctj1, cQj31, ctj8, ctd1, ctd8, ctGRe, ctGIm, cQj11, cQj18, ctu8, cQd8, ctu1, cQu1, cQj38, cQu8]
    model:
      n_trees: 400
      learning_rate: 0.2
      loss: MSE
      learn_global_score: true
      split_mode: "binned"
      n_bins: 256
      quantile_bins: true
    runtime:
      training_plots: true
    output:
      filename: "bit_TT01j2l_EFT_2018_allWC.pkl"

  - id: bit_TT01j2l_EFT_2018_halfWC
    type: bit
    region: SR
    process: TT01j2l_EFT_2018
    selection: null
    numba: True
    eft:
        parameters: [cQd1, ctj1, cQj31, ctj8]
    model:
      n_trees: 400
      learning_rate: 0.2
      loss: MSE
      learn_global_score: true
      split_mode: "binned"
      n_bins: 256
      quantile_bins: true
    runtime:
      training_plots: true
    output:
      filename: "bit_TT01j2l_EFT_2018_halfWC.pkl"
