# configs/training_tao_v1.yaml

# Number of epochs to train
n_epochs: 500

# Learning rate for the optimizer (Adam)
lr: 0.1

# Batch size (only used by your data loader)
batch_size: 1024

dtype: 'float32'

# Optional weight decay (L2 regularization) on the parameters
weight_decay: 0.0

loss: "MSE"

# Scheduler settings (optional – uncomment if you want LR scheduling)
#scheduler:
#  step_size: 10    # decay every N epochs
#  gamma: 0.1       # decay factor

# Early stopping (optional)
#early_stopping:
#  patience: 5      # stop if no improvement after this many epochs
#  min_delta: 1e-4  # minimum change to qualify as improvement

temperature: 1

# new regularization hyper‐parameters
l1:           0.001       # L1 strength
l2:           0.001 #1e-3       # L2 strength (weight decay)
