python icp_training.py --selection lowMT_VBFJet --config icp_quad_jes
python icp_training.py --selection lowMT_VBFJet --config icp_quad_tes
python icp_training.py --selection lowMT_VBFJet --config icp_quad_met
python icp_training.py --selection highMT_VBFJet --config icp_quad_jes
#python icp_training.py --selection highMT_VBFJet --config icp_quad_tes
#python icp_training.py --selection highMT_VBFJet --config icp_quad_met
#python icp_training.py --selection highMT_VBFJet --config icp_quad_jes
#python icp_training.py --selection highMT_VBFJet --config icp_quad_tes
#python icp_training.py --selection highMT_VBFJet --config icp_quad_met
#python icp_training.py --selection inclusive --config icp_quad_jes
#python icp_training.py --selection inclusive --config icp_quad_tes
#python icp_training.py --selection inclusive --config icp_quad_met
#python icp_training.py --selection lowMT_noVBFJet_ptH0to100 --config icp_quad_jes
#python icp_training.py --selection lowMT_noVBFJet_ptH0to100 --config icp_quad_tes
#python icp_training.py --selection lowMT_noVBFJet_ptH0to100 --config icp_quad_met
#python icp_training.py --selection lowMT_noVBFJet_ptH100 --config icp_quad_jes
#python icp_training.py --selection lowMT_noVBFJet_ptH100 --config icp_quad_tes
#python icp_training.py --selection lowMT_noVBFJet_ptH100 --config icp_quad_met
