#python icp_training.py --selection lowMT_VBFJet --config icp_quad_jes
#python icp_training.py --selection lowMT_VBFJet --config icp_quad_tes
#python icp_training.py --selection lowMT_VBFJet --config icp_quad_met
#python icp_training.py --selection highMT_VBFJet --config icp_quad_jes
#python icp_training.py --selection highMT_VBFJet --config icp_quad_tes
#python icp_training.py --selection highMT_VBFJet --config icp_quad_met
#python icp_training.py --selection highMT_VBFJet --config icp_quad_jes
#python icp_training.py --selection highMT_VBFJet --config icp_quad_tes
#python icp_training.py --selection highMT_VBFJet --config icp_quad_met
#python icp_training.py --selection inclusive --config icp_quad_jes
#python icp_training.py --selection inclusive --config icp_quad_tes
#python icp_training.py --selection inclusive --config icp_quad_met
#python icp_training.py --selection lowMT_noVBFJet_ptH0to100 --config icp_quad_jes
#python icp_training.py --selection lowMT_noVBFJet_ptH0to100 --config icp_quad_tes
#python icp_training.py --selection lowMT_noVBFJet_ptH0to100 --config icp_quad_met
#python icp_training.py --selection lowMT_noVBFJet_ptH100 --config icp_quad_jes
#python icp_training.py --selection lowMT_noVBFJet_ptH100 --config icp_quad_tes
#python icp_training.py --selection lowMT_noVBFJet_ptH100 --config icp_quad_met

python icp_training.py --config icp_quad_tes_jes_met --selection lowMT_VBFJet
python icp_training.py --config icp_quad_tes_jes_met --selection highMT_VBFJet
python icp_training.py --config icp_quad_tes_jes_met --selection lowMT_noVBFJet_ptH0to100
python icp_training.py --config icp_quad_tes_jes_met --selection lowMT_noVBFJet_ptH100
python icp_training.py --config icp_quad_tes_jes_met --selection highMT_noVBFJet_ptH0to100
python icp_training.py --config icp_quad_tes_jes_met --selection highMT_noVBFJet_ptH100

#python icp_training.py --config icp_quad_jes --selection lowMT_VBFJet
#python icp_training.py --config icp_quad_jes --selection highMT_VBFJet
#python icp_training.py --config icp_quad_jes --selection lowMT_noVBFJet_ptH0to100
#python icp_training.py --config icp_quad_jes --selection lowMT_noVBFJet_ptH100to200
#python icp_training.py --config icp_quad_jes --selection lowMT_noVBFJet_ptH200
#python icp_training.py --config icp_quad_jes --selection highMT_noVBFJet_ptH0to100
#python icp_training.py --config icp_quad_jes --selection highMT_noVBFJet_ptH100to200
#python icp_training.py --config icp_quad_jes --selection highMT_noVBFJet_ptH200
#
#python icp_training.py --config icp_quad_tes --selection lowMT_VBFJet
#python icp_training.py --config icp_quad_tes --selection highMT_VBFJet
#python icp_training.py --config icp_quad_tes --selection lowMT_noVBFJet_ptH0to100
#python icp_training.py --config icp_quad_tes --selection lowMT_noVBFJet_ptH100to200
#python icp_training.py --config icp_quad_tes --selection lowMT_noVBFJet_ptH200
#python icp_training.py --config icp_quad_tes --selection highMT_noVBFJet_ptH0to100
#python icp_training.py --config icp_quad_tes --selection highMT_noVBFJet_ptH100to200
#python icp_training.py --config icp_quad_tes --selection highMT_noVBFJet_ptH200
#
#python icp_training.py --config icp_quad_met --selection lowMT_VBFJet
#python icp_training.py --config icp_quad_met --selection highMT_VBFJet
#python icp_training.py --config icp_quad_met --selection lowMT_noVBFJet_ptH0to100
#python icp_training.py --config icp_quad_met --selection lowMT_noVBFJet_ptH100to200
#python icp_training.py --config icp_quad_met --selection lowMT_noVBFJet_ptH200
#python icp_training.py --config icp_quad_met --selection highMT_noVBFJet_ptH0to100
#python icp_training.py --config icp_quad_met --selection highMT_noVBFJet_ptH100to200
#python icp_training.py --config icp_quad_met --selection highMT_noVBFJet_ptH200
