#python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/nominal.h5 --selection highMT                --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/highMT
#python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/jes*.h5    --selection highMT                --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/highMT
#python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/tes*.h5    --selection highMT                --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/highMT
#python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/met*.h5    --selection highMT                --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/highMT

python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/nominal.h5 --selection highMT_VBFJet                --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/highMT_VBFJet
python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/jes*.h5    --selection highMT_VBFJet                --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/highMT_VBFJet
python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/tes*.h5    --selection highMT_VBFJet                --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/highMT_VBFJet
python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/met*.h5    --selection highMT_VBFJet                --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/highMT_VBFJet

python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/nominal.h5 --selection highMT_noVBFJet              --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/highMT_noVBFJet
python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/jes*.h5    --selection highMT_noVBFJet              --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/highMT_noVBFJet
python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/tes*.h5    --selection highMT_noVBFJet              --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/highMT_noVBFJet
python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/met*.h5    --selection highMT_noVBFJet              --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/highMT_noVBFJet

python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/nominal.h5 --selection lowMT_VBFJet                 --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/lowMT_VBFJet
python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/jes*.h5    --selection lowMT_VBFJet                 --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/lowMT_VBFJet
python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/tes*.h5    --selection lowMT_VBFJet                 --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/lowMT_VBFJet
python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/met*.h5    --selection lowMT_VBFJet                 --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/lowMT_VBFJet
#
#python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/nominal.h5 --selection GGHMVA_lowMT_noVBFJet_ptH0to100     --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/GGHMVA_lowMT_noVBFJet_ptH0to100
#python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/jes*.h5    --selection GGHMVA_lowMT_noVBFJet_ptH0to100     --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/GGHMVA_lowMT_noVBFJet_ptH0to100
#python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/tes*.h5    --selection GGHMVA_lowMT_noVBFJet_ptH0to100     --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/GGHMVA_lowMT_noVBFJet_ptH0to100
#python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/met*.h5    --selection GGHMVA_lowMT_noVBFJet_ptH0to100     --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/GGHMVA_lowMT_noVBFJet_ptH0to100

#python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/nominal.h5 --selection lowMT_noVBFJet_ptH0to100     --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/lowMT_noVBFJet_ptH0to100
#python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/jes*.h5    --selection lowMT_noVBFJet_ptH0to100     --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/lowMT_noVBFJet_ptH0to100
#python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/tes*.h5    --selection lowMT_noVBFJet_ptH0to100     --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/lowMT_noVBFJet_ptH0to100
#python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/met*.h5    --selection lowMT_noVBFJet_ptH0to100     --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/lowMT_noVBFJet_ptH0to100
#
python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/nominal.h5 --selection lowMT_noVBFJet_ptH100        --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/lowMT_noVBFJet_ptH100
python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/jes*.h5    --selection lowMT_noVBFJet_ptH100        --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/lowMT_noVBFJet_ptH100
python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/tes*.h5    --selection lowMT_noVBFJet_ptH100        --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/lowMT_noVBFJet_ptH100
python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/test/met*.h5    --selection lowMT_noVBFJet_ptH100        --target-dir /scratch-cbe/users/$USER/Higgs_uncertainty/test_data/lowMT_noVBFJet_ptH100
