#python  copy_with_selection.py --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/nominal.h5 --selection inclusive                   --target-dir /eos/vbc/group/cms/$USER/Higgs_uncertainty/data/inclusive
#python  copy_with_selection.py --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/jes*.h5    --selection inclusive                   --target-dir /eos/vbc/group/cms/$USER/Higgs_uncertainty/data/inclusive
#python  copy_with_selection.py --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/tes*.h5    --selection inclusive                   --target-dir /eos/vbc/group/cms/$USER/Higgs_uncertainty/data/inclusive
#python  copy_with_selection.py --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/met*.h5    --selection inclusive                   --target-dir /eos/vbc/group/cms/$USER/Higgs_uncertainty/data/inclusive
#
#python  aopy_with_selection.py --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/nominal.h5 --selection lowMT_VBFJet                   --target-dir /eos/vbc/group/cms/$USER/Higgs_uncertainty/data/lowMT_VBFJet
#python  copy_with_selection.py --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/jes*.h5    --selection lowMT_VBFJet                   --target-dir /eos/vbc/group/cms/$USER/Higgs_uncertainty/data/lowMT_VBFJet
#python  copy_with_selection.py --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/tes*.h5    --selection lowMT_VBFJet                   --target-dir /eos/vbc/group/cms/$USER/Higgs_uncertainty/data/lowMT_VBFJet
#python  copy_with_selection.py --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/met*.h5    --selection lowMT_VBFJet                   --target-dir /eos/vbc/group/cms/$USER/Higgs_uncertainty/data/lowMT_VBFJet
#
#python  copy_with_selection.py --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/nominal.h5 --selection highMT_VBFJet                   --target-dir /eos/vbc/group/cms/$USER/Higgs_uncertainty/data/highMT_VBFJet
#python  copy_with_selection.py --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/jes*.h5    --selection highMT_VBFJet                   --target-dir /eos/vbc/group/cms/$USER/Higgs_uncertainty/data/highMT_VBFJet
#python  copy_with_selection.py --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/tes*.h5    --selection highMT_VBFJet                   --target-dir /eos/vbc/group/cms/$USER/Higgs_uncertainty/data/highMT_VBFJet
#python  copy_with_selection.py --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/met*.h5    --selection highMT_VBFJet                   --target-dir /eos/vbc/group/cms/$USER/Higgs_uncertainty/data/highMT_VBFJet

python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/nominal.h5 --selection lowMT_noVBFJet_ptH0to100                   --target-dir /eos/vbc/group/cms/$USER/Higgs_uncertainty/data/lowMT_noVBFJet_ptH0to100
python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/jes*.h5    --selection lowMT_noVBFJet_ptH0to100                   --target-dir /eos/vbc/group/cms/$USER/Higgs_uncertainty/data/lowMT_noVBFJet_ptH0to100
python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/tes*.h5    --selection lowMT_noVBFJet_ptH0to100                   --target-dir /eos/vbc/group/cms/$USER/Higgs_uncertainty/data/lowMT_noVBFJet_ptH0to100
python  copy_with_selection.py --cmds --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/met*.h5    --selection lowMT_noVBFJet_ptH0to100                   --target-dir /eos/vbc/group/cms/$USER/Higgs_uncertainty/data/lowMT_noVBFJet_ptH0to100

#python  copy_with_selection.py --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/nominal.h5 --selection lowMT_noVBFJet_ptH100                   --target-dir /eos/vbc/group/cms/$USER/Higgs_uncertainty/data/lowMT_noVBFJet_ptH100
#python  copy_with_selection.py --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/jes*.h5    --selection lowMT_noVBFJet_ptH100                   --target-dir /eos/vbc/group/cms/$USER/Higgs_uncertainty/data/lowMT_noVBFJet_ptH100
#python  copy_with_selection.py --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/tes*.h5    --selection lowMT_noVBFJet_ptH100                   --target-dir /eos/vbc/group/cms/$USER/Higgs_uncertainty/data/lowMT_noVBFJet_ptH100
#python  copy_with_selection.py --n-batches 100 --files /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/met*.h5    --selection lowMT_noVBFJet_ptH100                   --target-dir /eos/vbc/group/cms/$USER/Higgs_uncertainty/data/lowMT_noVBFJet_ptH100
#
