# Toy spec for a truth-based toy study of BIT closure via exact reweighting (injection)
# at different values of Wilson coefficients.

source: truth              # or cache
split: [c2st_train, c2st_val] # partitions to use, truth mode only; null for the whole dataset
throw_nuisances: false
allow_negative_weights: true
# generation_point: {'cQd1': 1.5, 'ctj1': 1.5, 'cQj31': 1.5, 'ctj8': 1.5, 'ctd1': 1.5, 'ctd8': 1.5, 'ctGRe': -0.5, 'ctGIm': -0.5, 'cQj11': 1.5, 'cQj18': 1.5, 'ctu8': 1.5, 'cQd8': 1.5, 'ctu1': 1.5, 'cQu1': 1.5, 'cQj38': 1.5, 'cQu8': 1.5}

points:

  # all coefficients at generation point, ctG(...) = -0.5, others = 1.5
  - name: nominal

  # all of the coefficients in the POI configs not provided are kept at the generation point
  - name: ctGRe_sm
    injection:
      SR_2016:
        TT01j2l_EFT_2016:
          coefficients: {ctGRe: 0.0}

  - name: ctGRe_0p5
    injection:
      SR_2016:
        TT01j2l_EFT_2016:
          coefficients: {ctGRe: 0.5}

  - name: ctGRe_1p0
    injection:
      SR_2016:
        TT01j2l_EFT_2016:
          coefficients: {ctGRe: 1.0}

  - name: ctGRe_1p5
    injection:
      SR_2016:
        TT01j2l_EFT_2016:
          coefficients: {ctGRe: 1.5}

  - name: ctGRe_m1p0
    injection:
      SR_2016:
        TT01j2l_EFT_2016:
          coefficients: {ctGRe: -1.0}

  - name: ctGRe_m1p5
    injection:
      SR_2016:
        TT01j2l_EFT_2016:
          coefficients: {ctGRe: -1.5}
  
  - name: ctGIm_sm
    injection:
      SR_2016:
        TT01j2l_EFT_2016:
          coefficients: {ctGIm: 0.0}

  - name: ctGIm_0p5
    injection:
      SR_2016:
        TT01j2l_EFT_2016:
          coefficients: {ctGIm: 0.5}

  - name: ctGIm_1p0
    injection:
      SR_2016:
        TT01j2l_EFT_2016:
          coefficients: {ctGIm: 1.0}

  - name: ctGIm_1p5
    injection:
      SR_2016:
        TT01j2l_EFT_2016:
          coefficients: {ctGIm: 1.5}

  - name: ctGIm_m1p0
    injection:
      SR_2016:
        TT01j2l_EFT_2016:
          coefficients: {ctGIm: -1.0}

  - name: ctGIm_m1p5
    injection:
      SR_2016:
        TT01j2l_EFT_2016:
          coefficients: {ctGIm: -1.5}

  - name: ctGRe_ctGIm_sm
    injection:
      SR_2016:
        TT01j2l_EFT_2016:
          coefficients: {ctGRe: 0.0, ctGIm: 0.0}

  - name: ctGRe_ctGIm_0p5
    injection:
      SR_2016:
        TT01j2l_EFT_2016:
          coefficients: {ctGRe: 0.5, ctGIm: 0.5}

# cQj18

  - name: cQj18_sm
    injection:
      SR_2016:
        TT01j2l_EFT_2016:
          coefficients: {cQj18: 0.0}

  - name: cQj18_sm_BIT
    hypothesis: {cQj18: 0.0}

  - name: cQj18_0p5
    injection:
      SR_2016:
        TT01j2l_EFT_2016:
          coefficients: {cQj18: 0.5}

  - name: cQj18_3p0
    injection:
      SR_2016:
        TT01j2l_EFT_2016:
          coefficients: {cQj18: 3.0}

  - name: cQj18_1p0
    injection:
      SR_2016:
        TT01j2l_EFT_2016:
          coefficients: {cQj18: 1.0}

  - name: cQj18_2p0
    injection:
      SR_2016:
        TT01j2l_EFT_2016:
            coefficients: {cQj18: 2.0}

  - name: cQj18_2p5
    injection:
      SR_2016:
        TT01j2l_EFT_2016:
            coefficients: {cQj18: 2.5}

  - name: cQj18_m1p0
    injection:
      SR_2016:
        TT01j2l_EFT_2016:
          coefficients: {cQj18: -1.0}

  - name: cQj18_m1p5
    injection:
      SR_2016:
        TT01j2l_EFT_2016:
          coefficients: {cQj18: -1.5}

  - name: ctGRe_ctGIm_cQj18_sm
    injection:
      SR_2016:
        TT01j2l_EFT_2016:
          coefficients: {ctGRe: 0.0, ctGIm: 0.0, cQj18: 0.0}

  - name: ctGRe_ctGIm_cQj18_sm_BIT
    hypothesis: {ctGRe: 0.0, ctGIm: 0.0, cQj18: 0.0}

  - name: ctGRe_ctGIm_cQj18_0p5
    injection:
      SR_2016:
        TT01j2l_EFT_2016:
          coefficients: {ctGRe: 0.5, cQj18: 0.5}

# ctj1 + others (ML4EFT_top4)

  - name: ctj1_sm
    injection:
    SR_2016:
      TT01j2l_EFT_2016:
        coefficients: {ctj1: 0.0}

  - name: ML4EFT_top4_sm
    injection:
    SR_2016:
      TT01j2l_EFT_2016:
        coefficients: {ctGRe: 0.0, ctGIm: 0.0, cQj18: 0.0, ctj1: 0.0}

# cQu8 + others (ML4EFT_top5)

  - name: cQu8_sm
    injection:
    SR_2016:
      TT01j2l_EFT_2016:
        coefficients: {cQu8: 0.0}

  - name: ML4EFT_top5_sm
    injection:
    SR_2016:
      TT01j2l_EFT_2016:
        coefficients: {ctGRe: 0.0, ctGIm: 0.0, cQj18: 0.0, ctj1: 0.0, cQu8: 0.0}

# ctu8 + others (ML4EFT_top6)

  - name: ctu8_sm
    injection:
    SR_2016:
      TT01j2l_EFT_2016:
        coefficients: {ctu8: 0.0}

  - name: ML4EFT_top6_sm
    injection:
    SR_2016:
      TT01j2l_EFT_2016:
        coefficients: {ctGRe: 0.0, ctGIm: 0.0, cQj18: 0.0, ctj1: 0.0, cQu8: 0.0, ctu8: 0.0}

# cQd8 + others (ML4EFT_top7)

  - name: cQd8_sm
    injection:
    SR_2016:
      TT01j2l_EFT_2016:
        coefficients: {cQd8: 0.0}

  - name: ML4EFT_top7_sm
    injection:
    SR_2016:
      TT01j2l_EFT_2016:
        coefficients: {ctGRe: 0.0, ctGIm: 0.0, cQj18: 0.0, ctj1: 0.0, cQu8: 0.0, ctu8: 0.0, cQd8: 0.0}

  # ctd8 + others (ML4EFT_top8)

  - name: ctd8_sm
    injection:
    SR_2016:
      TT01j2l_EFT_2016:
        coefficients: {ctd8: 0.0}

  - name: ML4EFT_top8_sm
    injection:
    SR_2016:
      TT01j2l_EFT_2016:
        coefficients: {ctGRe: 0.0, ctGIm: 0.0, cQj18: 0.0, ctj1: 0.0, cQu8: 0.0, ctu8: 0.0, cQd8: 0.0, ctd8: 0.0}

  # cQj38 + others (ML4EFT_top9)

  - name: cQj38_sm
    injection:
    SR_2016:
      TT01j2l_EFT_2016:
        coefficients: {cQj38: 0.0}

  - name: ML4EFT_top9_sm
    injection:
    SR_2016:
      TT01j2l_EFT_2016:
        coefficients: {ctGRe: 0.0, ctGIm: 0.0, cQj18: 0.0, ctj1: 0.0, cQu8: 0.0, ctu8: 0.0, cQd8: 0.0, ctd8: 0.0, cQj38: 0.0}

  # all WC
  - name: allWC_sm
    injection:
    SR_2016:
      TT01j2l_EFT_2016:
        coefficients: {ctGRe: 0.0, ctGIm: 0.0, cQj18: 0.0, ctj1: 0.0, cQu8: 0.0, ctu8: 0.0, cQd8: 0.0, ctd8: 0.0, cQj38: 0.0, cQd1: 0.0, ctj1: 0.0, cQj31: 0.0, cQj11: 0.0, ctu1: 0.0, cQu1: 0.0}