version: unbinned_v7_eft_genpoint

defaults:
  module_samples: "data.samples_eft"
  default_features:
    - TOP_KINEMATICS
    - LEPTON_KINEMATICS
    - ASYMMETRY
    - SPIN_CORRELATION

  default_selection: tr_ttbar_pt < 1500

  default_selection_features:
    - tr_ttbar_pt

  splitting:
    enabled: true
    type: uid
    uid_fields: ["run", "luminosityBlock", "event"]
    seed: 42
    n_buckets: 10000 

    scheme:
      pnn_train:     { fraction: 0.50 }
      pnn_val:       { fraction: 0.10 }
      c2st_train:    { fraction: 0.15 }
      c2st_val:      { fraction: 0.05 }
      final_eval:    { fraction: 0.20 }

  early_stopping:
    enabled: true
    patience: 20        # same as current hard-coded
    min_delta: 0.0      # improvement threshold; keep 0.0 to match current behavior
    mode: "min"         # val_loss should decrease
    warmup_epochs: 0    # optional: do not early-stop before this epoch


likelihood:
    regions:
        - id: SR_2016 
          classifier:
            type: null
            id: null    # no classifier needed for a single process
            asimov: [TT01j2l_EFT_2016]
          classes: 
            - id: TT01j2l_EFT_2016
              sample: TT01j2l_EFT_2016 
              POI:
                job: bit_TT01j2l_EFT_2016_allWC 
                type: bit
                parameters: [cQd1, ctj1, cQj31, ctj8, ctd1, ctd8, ctGRe, ctGIm, cQj11, cQj18, ctu8, cQd8, ctu1, cQu1, cQj38, cQu8]

jobs:

  - id: bit_TT01j2l_EFT_2016_allWC
    type: bit
    region: SR_2016
    process: TT01j2l_EFT_2016
    selection: null
    numba: True
    eft:
        parameters: [cQd1, ctj1, cQj31, ctj8, ctd1, ctd8, ctGRe, ctGIm, cQj11, cQj18, ctu8, cQd8, ctu1, cQu1, cQj38, cQu8]
    model:
      n_trees: 400
      learning_rate: 0.2
      loss: MSE
      learn_global_score: true
      split_mode: "binned"
      n_bins: 256
      quantile_bins: true
    runtime:
      training_plots: true
    output:
      filename: "bit_TT01j2l_EFT_2016_allWC.pkl"