python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 0
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 0.1
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 0.2
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 0.3
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 0.4
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 0.5
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 0.6
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 0.7
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 0.8
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 0.9
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 1.0
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 1.1
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 1.2
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 1.3
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 1.4
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 1.5
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 1.6
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 1.7
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 1.8
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 1.9
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 2.0
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 2.1
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 2.2
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 2.3
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 2.4
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 2.5
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 2.6
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 2.7
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 2.8
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 2.9
python asimovFit.py --config ../../Workflow/configs/config_reference_v5-v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 3.0

#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 0
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 0.1
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 0.2
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 0.3
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 0.4
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 0.5
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 0.6
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 0.7
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 0.8
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 0.9
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 1.0
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 1.1
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 1.2
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 1.3
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 1.4
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 1.5
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 1.6
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 1.7
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 1.8
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 1.9
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 2.0
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 2.1
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 2.2
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 2.3
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 2.4
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 2.5
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 2.6
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 2.7
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 2.8
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 2.9
#python asimovFit.py --config ../../Workflow/configs/config_binned_v2.yaml --logLevel DEBUG --asimov_mu 1.0 --fixed_mu 3.0
