python plot.py --selection inclusive
python plot.py --selection lowMT
python plot.py --selection highMT
python plot.py --selection VBFJet
python plot.py --selection noVBFJet
python plot.py --selection ptH0to50
python plot.py --selection ptH50to100
python plot.py --selection ptH100to200
python plot.py --selection ptH100
python plot.py --selection ptH200
python plot.py --selection lowMT_VBFJet
python plot.py --selection highMT_VBFJet
python plot.py --selection lowMT_noVBFJet_ptH0to50
python plot.py --selection lowMT_noVBFJet_ptH50to100
python plot.py --selection lowMT_noVBFJet_ptH100to200
python plot.py --selection lowMT_noVBFJet_ptH100
python plot.py --selection lowMT_noVBFJet_ptH200
python plot.py --selection highMT_noVBFJet_ptH0to50
python plot.py --selection highMT_noVBFJet_ptH50to100
python plot.py --selection highMT_noVBFJet_ptH100to200
python plot.py --selection highMT_noVBFJet_ptH100
python plot.py --selection highMT_noVBFJet_ptH200
