python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --prefit --var PRI_lep_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --prefit --var PRI_lep_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --prefit --var PRI_lep_phi,PRI_had_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --prefit --var PRI_had_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --prefit --var PRI_had_phi,PRI_jet_leading_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --prefit --var PRI_jet_leading_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --prefit --var PRI_jet_leading_phi,PRI_jet_subleading_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --prefit --var PRI_jet_subleading_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --prefit --var PRI_jet_subleading_phi,PRI_n_jets,PRI_jet_all_pt,PRI_met
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --prefit --var PRI_met_phi
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --prefit --var DER_mass_transverse_met_lep
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --prefit --var DER_mass_vis
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --prefit --var DER_pt_h
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --prefit --var DER_deltaeta_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --prefit --var DER_mass_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --prefit --var DER_prodeta_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --prefit --var DER_deltar_had_lep
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --prefit --var DER_pt_tot
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --prefit --var DER_sum_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --prefit --var DER_pt_ratio_lep_tau
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --prefit --var DER_met_phi_centrality
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --prefit --var DER_lep_eta_centrality

python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --var PRI_lep_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --var PRI_lep_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --var PRI_lep_phi,PRI_had_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --var PRI_had_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --var PRI_had_phi,PRI_jet_leading_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --var PRI_jet_leading_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --var PRI_jet_leading_phi,PRI_jet_subleading_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --var PRI_jet_subleading_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --var PRI_jet_subleading_phi,PRI_n_jets,PRI_jet_all_pt,PRI_met
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --var PRI_met_phi
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --var DER_mass_transverse_met_lep
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --var DER_mass_vis
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --var DER_pt_h
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --var DER_deltaeta_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --var DER_mass_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --var DER_prodeta_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --var DER_deltar_had_lep
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --var DER_pt_tot
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --var DER_sum_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --var DER_pt_ratio_lep_tau
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --var DER_met_phi_centrality
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_1.h5  --var DER_lep_eta_centrality

python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --prefit --var PRI_lep_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --prefit --var PRI_lep_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --prefit --var PRI_lep_phi,PRI_had_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --prefit --var PRI_had_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --prefit --var PRI_had_phi,PRI_jet_leading_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --prefit --var PRI_jet_leading_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --prefit --var PRI_jet_leading_phi,PRI_jet_subleading_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --prefit --var PRI_jet_subleading_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --prefit --var PRI_jet_subleading_phi,PRI_n_jets,PRI_jet_all_pt,PRI_met
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --prefit --var PRI_met_phi
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --prefit --var DER_mass_transverse_met_lep
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --prefit --var DER_mass_vis
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --prefit --var DER_pt_h
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --prefit --var DER_deltaeta_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --prefit --var DER_mass_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --prefit --var DER_prodeta_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --prefit --var DER_deltar_had_lep
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --prefit --var DER_pt_tot
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --prefit --var DER_sum_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --prefit --var DER_pt_ratio_lep_tau
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --prefit --var DER_met_phi_centrality
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --prefit --var DER_lep_eta_centrality

python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --var PRI_lep_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --var PRI_lep_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --var PRI_lep_phi,PRI_had_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --var PRI_had_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --var PRI_had_phi,PRI_jet_leading_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --var PRI_jet_leading_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --var PRI_jet_leading_phi,PRI_jet_subleading_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --var PRI_jet_subleading_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --var PRI_jet_subleading_phi,PRI_n_jets,PRI_jet_all_pt,PRI_met
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --var PRI_met_phi
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --var DER_mass_transverse_met_lep
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --var DER_mass_vis
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --var DER_pt_h
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --var DER_deltaeta_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --var DER_mass_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --var DER_prodeta_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --var DER_deltar_had_lep
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --var DER_pt_tot
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --var DER_sum_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --var DER_pt_ratio_lep_tau
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --var DER_met_phi_centrality
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_2.h5  --var DER_lep_eta_centrality

python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --prefit --var PRI_lep_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --prefit --var PRI_lep_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --prefit --var PRI_lep_phi,PRI_had_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --prefit --var PRI_had_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --prefit --var PRI_had_phi,PRI_jet_leading_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --prefit --var PRI_jet_leading_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --prefit --var PRI_jet_leading_phi,PRI_jet_subleading_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --prefit --var PRI_jet_subleading_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --prefit --var PRI_jet_subleading_phi,PRI_n_jets,PRI_jet_all_pt,PRI_met
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --prefit --var PRI_met_phi
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --prefit --var DER_mass_transverse_met_lep
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --prefit --var DER_mass_vis
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --prefit --var DER_pt_h
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --prefit --var DER_deltaeta_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --prefit --var DER_mass_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --prefit --var DER_prodeta_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --prefit --var DER_deltar_had_lep
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --prefit --var DER_pt_tot
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --prefit --var DER_sum_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --prefit --var DER_pt_ratio_lep_tau
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --prefit --var DER_met_phi_centrality
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --prefit --var DER_lep_eta_centrality

python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --var PRI_lep_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --var PRI_lep_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --var PRI_lep_phi,PRI_had_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --var PRI_had_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --var PRI_had_phi,PRI_jet_leading_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --var PRI_jet_leading_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --var PRI_jet_leading_phi,PRI_jet_subleading_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --var PRI_jet_subleading_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --var PRI_jet_subleading_phi,PRI_n_jets,PRI_jet_all_pt,PRI_met
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --var PRI_met_phi
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --var DER_mass_transverse_met_lep
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --var DER_mass_vis
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --var DER_pt_h
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --var DER_deltaeta_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --var DER_mass_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --var DER_prodeta_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --var DER_deltar_had_lep
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --var DER_pt_tot
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --var DER_sum_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --var DER_pt_ratio_lep_tau
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --var DER_met_phi_centrality
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_3.h5  --var DER_lep_eta_centrality

python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --prefit --var PRI_lep_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --prefit --var PRI_lep_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --prefit --var PRI_lep_phi,PRI_had_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --prefit --var PRI_had_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --prefit --var PRI_had_phi,PRI_jet_leading_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --prefit --var PRI_jet_leading_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --prefit --var PRI_jet_leading_phi,PRI_jet_subleading_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --prefit --var PRI_jet_subleading_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --prefit --var PRI_jet_subleading_phi,PRI_n_jets,PRI_jet_all_pt,PRI_met
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --prefit --var PRI_met_phi
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --prefit --var DER_mass_transverse_met_lep
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --prefit --var DER_mass_vis
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --prefit --var DER_pt_h
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --prefit --var DER_deltaeta_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --prefit --var DER_mass_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --prefit --var DER_prodeta_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --prefit --var DER_deltar_had_lep
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --prefit --var DER_pt_tot
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --prefit --var DER_sum_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --prefit --var DER_pt_ratio_lep_tau
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --prefit --var DER_met_phi_centrality
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --prefit --var DER_lep_eta_centrality

python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --var PRI_lep_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --var PRI_lep_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --var PRI_lep_phi,PRI_had_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --var PRI_had_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --var PRI_had_phi,PRI_jet_leading_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --var PRI_jet_leading_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --var PRI_jet_leading_phi,PRI_jet_subleading_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --var PRI_jet_subleading_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --var PRI_jet_subleading_phi,PRI_n_jets,PRI_jet_all_pt,PRI_met
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --var PRI_met_phi
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --var DER_mass_transverse_met_lep
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --var DER_mass_vis
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --var DER_pt_h
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --var DER_deltaeta_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --var DER_mass_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --var DER_prodeta_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --var DER_deltar_had_lep
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --var DER_pt_tot
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --var DER_sum_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --var DER_pt_ratio_lep_tau
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --var DER_met_phi_centrality
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_4.h5  --var DER_lep_eta_centrality

python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --prefit --var PRI_lep_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --prefit --var PRI_lep_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --prefit --var PRI_lep_phi,PRI_had_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --prefit --var PRI_had_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --prefit --var PRI_had_phi,PRI_jet_leading_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --prefit --var PRI_jet_leading_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --prefit --var PRI_jet_leading_phi,PRI_jet_subleading_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --prefit --var PRI_jet_subleading_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --prefit --var PRI_jet_subleading_phi,PRI_n_jets,PRI_jet_all_pt,PRI_met
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --prefit --var PRI_met_phi
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --prefit --var DER_mass_transverse_met_lep
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --prefit --var DER_mass_vis
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --prefit --var DER_pt_h
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --prefit --var DER_deltaeta_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --prefit --var DER_mass_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --prefit --var DER_prodeta_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --prefit --var DER_deltar_had_lep
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --prefit --var DER_pt_tot
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --prefit --var DER_sum_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --prefit --var DER_pt_ratio_lep_tau
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --prefit --var DER_met_phi_centrality
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --prefit --var DER_lep_eta_centrality

python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --var PRI_lep_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --var PRI_lep_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --var PRI_lep_phi,PRI_had_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --var PRI_had_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --var PRI_had_phi,PRI_jet_leading_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --var PRI_jet_leading_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --var PRI_jet_leading_phi,PRI_jet_subleading_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --var PRI_jet_subleading_eta
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --var PRI_jet_subleading_phi,PRI_n_jets,PRI_jet_all_pt,PRI_met
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --var PRI_met_phi
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --var DER_mass_transverse_met_lep
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --var DER_mass_vis
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --var DER_pt_h
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --var DER_deltaeta_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --var DER_mass_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --var DER_prodeta_jet_jet
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --var DER_deltar_had_lep
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --var DER_pt_tot
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --var DER_sum_pt
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --var DER_pt_ratio_lep_tau
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --var DER_met_phi_centrality
python postFit_plot.py --config ../../Workflow/configs/config_reference_v5-v2.yaml  --toy /eos/vbc/group/mlearning/data/Higgs_uncertainty/input_data/split_train_dataset/processed_data/pseudo_experiments_with_true_labels_mu_3/set_3.0_pseudo_exp_5.h5  --var DER_lep_eta_centrality

