version: unbinned_v6

defaults:
  module_samples: "data.samples_RunII"
  default_features:
    - TOP_KINEMATICS
    - LEPTON_KINEMATICS
    - ASYMMETRY

  splitting:
    enabled: true
    uid_fields: ["run", "luminosityBlock", "event"]
    seed: 42
    n_buckets: 10000 

    scheme:
      pnn_train:     { fraction: 0.50 }
      pnn_val:       { fraction: 0.10 }
      c2st_train:    { fraction: 0.15 }
      c2st_val:      { fraction: 0.05 }
      final_eval:    { fraction: 0.20 }

  early_stopping:
    enabled: true
    patience: 20        # same as current hard-coded
    min_delta: 0.0      # improvement threshold; keep 0.0 to match current behavior
    mode: "min"         # val_loss should decrease
    warmup_epochs: 0    # optional: do not early-stop before this epoch

likelihood:
    regions:
        - id: SR_2018
          data:
            id: Data_2018
            sample: Data_2018                  
          classifier:
            # does this make sense as "type"? shouldn't it be "framework" to match what's in the job ?
            type: tfmc
            job: tfmc_2018_DY_LO
            asimov: [TTLep_pow_2018, SingleTop_2018, DrellYan_LO_HTbinned_2018, TTSemi_pow_2018]
          classes: 
            - id: TTLep_pow_2018
              sample: TTLep_pow_2018
              POI:
                job: bit_NG_PDF4LHC21_6_TTLep_pow_2018 
                type: bit
                parameters: [c0, c1, c2, c3, c4, c5]

              systematics:
                - id: signal_strength
                  type: lnN
                  value: 0.036 # twice the relative uncertainty on the ATLAS measurement
                  parameters: [nu_norm_ttbar]
                  floating: true                  
                - id: Lumi_15161718
                  type: lnN
                  value: 0.0084              
                  parameters: [nu_lumi_15161718]              
                - id: L1Prefire
                  type: pnn
                  job: pnn_TTLep_pow_2018_L1Prefire
                  parameters: [nu_l1prefire]
                - id: CMS_scale_j_Regrouped_Absolute_2018
                  type: pnn
                  job: pnn_TTLep_pow_2018_CMS_scale_j_Regrouped_Absolute_2018
                  parameters: [nu_CMS_scale_j_Regrouped_Absolute_2018]
                - id: CMS_scale_j_Regrouped_Absolute
                  type: pnn
                  job: pnn_TTLep_pow_2018_CMS_scale_j_Regrouped_Absolute
                  parameters: [nu_CMS_scale_j_Regrouped_Absolute]

jobs:

  - id: tfmc_2018_DY_LO 
    type: classifier
    region: SR_2018
    framework: "tfmc"
    data:
      classes: [TTLep_pow_2018, SingleTop_2018, DrellYan_LO_HTbinned_2018, TTSemi_pow_2018]
    model:
      activation: relu
      hidden_layers: [128, 128, 128]
      # dropout_rate: 0.25  
    optim:
      epochs: 500
      phaseout_epochs: 150
      learning_rate: 0.02
    set_logit_priors: true
    runtime:
      batch_size: 16384
    early_stopping:
      enabled: true
      patience: 50        
      min_delta: 0.0
      mode: "min"
      warmup_epochs: 100        
    extras:
      use_scaler: scaler_TTLep_pow_2018
    output:
      filename: "tfmc_2018_DY_LO.pkl"

  - id: bit_NG_PDF4LHC21_6_TTLep_pow_2018
    type: bit
    region: SR_2018
    process: TTLep_pow_2018
    selection: null               # optional extra selection layered on top
    numba: True
    pdf:
      pdf_n: [1,2,3,4,5,6]
      pdf_type: PODBasis
      pdf_basis: gluon_POD_nongluon_PDF4LHC21 
    model:
      n_trees: 200
      learning_rate: 0.2
      loss: MSE                   # or "CrossEntropy"
      learn_global_score: true
      split_mode: "binned"
      n_bins: 256
      quantile_bins: true  # if True: quantile edges; else uniform edges
    runtime:
      training_plots: true        # keep if you want training plots
    output:
      filename: "BIT_NG_PDF4LHC21_6_TTLep_pow_2018.pkl"

  - id: scaler_TTLep_pow_2018
    type: scaler
    process: TTLep_pow_2018
    region: SR_2018
    selection: null
    output:
      filename: "Scaler_TTLep_pow_2018.pkl"

  - id: icp_TTLep_pow_2018_L1Prefire
    type: icp
    region: SR_2018
    parameters: [nu_l1prefire]
    combinations: [[nu_l1prefire]]
    base_points:
    - coords: [-1.0]
      loader: TTLep_pow_2018
      removeweights: ["L1PreFiringWeight_Nom"]
      addweights: ["L1PreFiringWeight_Dn"]
    - coords: [0.0]
      loader: TTLep_pow_2018
      nominal: true
    - coords: [1.0]
      loader: TTLep_pow_2018
      removeweights: ["L1PreFiringWeight_Nom"]
      addweights: ["L1PreFiringWeight_Up"]
    train_ratio: true
    output:
      filename: icp_TTLep_pow_2018_L1Prefire.pkl

  - id: pnn_TTLep_pow_2018_L1Prefire
    type: pnn
    region: SR_2018
    parameters: [nu_l1prefire]
    combinations: [[nu_l1prefire]]
    base_points:
    - coords: [-1.0]
      loader: TTLep_pow_2018
      removeweights: ["L1PreFiringWeight_Nom"]
      addweights: ["L1PreFiringWeight_Dn"]
    - coords: [0.0]
      loader: TTLep_pow_2018
      nominal: true
    - coords: [1.0]
      loader: TTLep_pow_2018
      removeweights: ["L1PreFiringWeight_Nom"]
      addweights: ["L1PreFiringWeight_Up"]
    model:
      hidden_layers:
      - 128
      - 128
      activation: relu
      initialize_zero: true
    optim:
      epochs: 200
      phaseout_epochs: 50
      learning_rate: 0.001
    runtime:
      n_split: 10
      rebin: 2
    extras:
      use_scaler: scaler_TTLep_pow_2018
      use_icp: icp_TTLep_pow_2018_L1Prefire

  - id: icp_TTLep_pow_2018_CMS_scale_j_Regrouped_Absolute_2018
    type: icp
    region: SR_2018
    parameters: [nu_CMS_scale_j_Regrouped_Absolute_2018]
    combinations: [[nu_CMS_scale_j_Regrouped_Absolute_2018]]
    base_points:
    - coords: [-1.0]
      loader: TTLep_pow_2018_CMS_scale_j_Regrouped_Absolute_2018_down
    - coords: [0]
      loader: TTLep_pow_2018
      nominal: true
    - coords: [1.0]
      loader: TTLep_pow_2018_CMS_scale_j_Regrouped_Absolute_2018_up
  
    train_ratio: true
    output:
      filename: icp_TTLep_pow_2018_CMS_scale_j_Regrouped_Absolute_2018.pkl
  - id: pnn_TTLep_pow_2018_CMS_scale_j_Regrouped_Absolute_2018
    type: pnn
    region: SR_2018
    parameters: [nu_CMS_scale_j_Regrouped_Absolute_2018]
    combinations: [[nu_CMS_scale_j_Regrouped_Absolute_2018]]
    base_points:
    - coords: [-1.0]
      loader: TTLep_pow_2018_CMS_scale_j_Regrouped_Absolute_2018_down
    - coords: [0]
      loader: TTLep_pow_2018
      nominal: true
    - coords: [1.0]
      loader: TTLep_pow_2018_CMS_scale_j_Regrouped_Absolute_2018_up
  
    model:
      hidden_layers:
      - 128
      - 128
      activation: relu
      initialize_zero: true
    optim:
      epochs: 200
      phaseout_epochs: 50
      learning_rate: 0.001
    runtime:
      n_split: 10
      rebin: 2
    extras:
      use_scaler: scaler_TTLep_pow_2018
      use_icp: icp_TTLep_pow_2018_CMS_scale_j_Regrouped_Absolute_2018
  - id: icp_TTLep_pow_2018_CMS_scale_j_Regrouped_Absolute
    type: icp
    region: SR_2018
    parameters: [nu_CMS_scale_j_Regrouped_Absolute]
    combinations: [[nu_CMS_scale_j_Regrouped_Absolute]]
    base_points:
    - coords: [-1.0]
      loader: TTLep_pow_2018_CMS_scale_j_Regrouped_Absolute_down
    - coords: [0]
      loader: TTLep_pow_2018
      nominal: true
    - coords: [1.0]
      loader: TTLep_pow_2018_CMS_scale_j_Regrouped_Absolute_up
    train_ratio: true
    output:
      filename: icp_TTLep_pow_2018_CMS_scale_j_Regrouped_Absolute.pkl

  - id: pnn_TTLep_pow_2018_CMS_scale_j_Regrouped_Absolute
    type: pnn
    region: SR_2018
    parameters: [nu_CMS_scale_j_Regrouped_Absolute]
    combinations: [[nu_CMS_scale_j_Regrouped_Absolute]]
    base_points:
    - coords: [-1.0]
      loader: TTLep_pow_2018_CMS_scale_j_Regrouped_Absolute_down
    - coords: [0]
      loader: TTLep_pow_2018
      nominal: true
    - coords: [1.0]
      loader: TTLep_pow_2018_CMS_scale_j_Regrouped_Absolute_up
    model:
      hidden_layers:
      - 128
      - 128
      activation: relu
      initialize_zero: true
    optim:
      epochs: 200
      phaseout_epochs: 50
      learning_rate: 0.001
    runtime:
      n_split: 10
      rebin: 2
    extras:
      use_scaler: scaler_TTLep_pow_2018
      use_icp: icp_TTLep_pow_2018_CMS_scale_j_Regrouped_Absolute
