version: v1

defaults:
  module_samples: "data.samples"     
  batch_size: 65536

likelihood:
    binned:
        - id: SR_binned 
          asimov: [tt2l]
          classes:
            - id: tt2l
              sample: tt2l
              POI:
                job: ich_tt2l
                type: ich
                parameters: [c0, c1, c2, c3, c4, c5]
              systematics: 
                - id: Normalization
                  type: lnN
                  value: 0.05 
                  parameters: [nu_norm]
                - id: Trigger
                  type: icph
                  job: icph_tt2l_Trigger
                  parameters: [nu_trigger]
                - id: L1Prefire
                  type: icph
                  job: icph_tt2l_L1Prefire
                  parameters: [nu_l1prefire]
                - id: PU
                  type: icph
                  job: icph_tt2l_PU
                  parameters: [nu_pu]
                - id: LeptonSF
                  type: icph
                  job: icph_tt2l_LeptonSF
                  parameters: [nu_leptonsf]
                - id: BTag_b
                  type: icph
                  job: icph_tt2l_BTag_b
                  parameters: [nu_btag_b]
                - id: BTag_l
                  type: icph
                  job: icph_tt2l_BTag_l
                  parameters: [nu_btag_l]
                - id: Scales
                  type: icph
                  job: icph_tt2l_scales
                  parameters: [nu_mu_ren, nu_mu_fac]
                - id: JES
                  type: icph
                  job: icph_tt2l_jesTotal
                  parameters: [nu_jes]

jobs:
  - id: ich_tt2l
    type: ich
    region: SR_binned
    process: tt2l
    binning:
      - ["tr_ttbar_mass", [500, 620, 820, 1100, 1500, 2500]]
      #- ["tr_ttbar_pt",   [-1e9, 300, 1e9]]
    pdf:
      cheb_n: 5                   
    output: {filename: "ICH_tt2l.pkl"}

  - id: icph_tt2l_Trigger
    type: icph
    region: SR_binned
    parameters: [nu_trigger]
    combinations: [[nu_trigger]]
    binning:
      - ["tr_ttbar_mass", [500, 620, 820, 1100, 1500, 2500]]
      #- ["tr_ttbar_pt",   [-1e9, 300, 1e9]]
    base_points:
      - coords: [-1.0]
        loader: tt2l
        removeweights: ["reweightTrigger"] 
        addweights: ["reweightTriggerDown"] 
      - coords: [ 0.0]
        loader: tt2l
        nominal: true
      - coords: [ 1.0]
        loader: tt2l
        removeweights: ["reweightTrigger"] 
        addweights: ["reweightTriggerUp"] 
    output: { filename: "icph_tt2l_Trigger.pkl" }
  
  - id: icph_tt2l_L1Prefire
    type: icph
    region: SR_binned
    parameters: [nu_l1prefire]
    combinations: [[nu_l1prefire]]
    binning:
      - ["tr_ttbar_mass", [500, 620, 820, 1100, 1500, 2500]]
      #- ["tr_ttbar_pt",   [-1e9, 300, 1e9]]
    base_points:
      - coords: [-1.0]
        loader: tt2l
        removeweights: ["reweightL1Prefire"] 
        addweights: ["reweightL1PrefireDown"] 
      - coords: [ 0.0]
        loader: tt2l
        nominal: true
      - coords: [ 1.0]
        loader: tt2l
        removeweights: ["reweightL1Prefire"] 
        addweights: ["reweightL1PrefireUp"] 
    output: { filename: "icph_tt2l_L1Prefire.pkl" }
  
  - id: icph_tt2l_PU
    type: icph
    region: SR_binned
    parameters: [nu_pu]
    combinations: [[nu_pu]]
    binning:
      - ["tr_ttbar_mass", [500, 620, 820, 1100, 1500, 2500]]
      #- ["tr_ttbar_pt",   [-1e9, 300, 1e9]]
    base_points:
      - coords: [-1.0]
        loader: tt2l
        removeweights: ["reweightPU"] 
        addweights: ["reweightPUDown"] 
      - coords: [ 0.0]
        loader: tt2l
        nominal: true
      - coords: [ 1.0]
        loader: tt2l
        removeweights: ["reweightPU"] 
        addweights: ["reweightPUUp"] 
    output: { filename: "icph_tt2l_PU.pkl" }

 
  - id: icph_tt2l_LeptonSF
    type: icph
    region: SR_binned
    parameters: [nu_leptonsf]
    combinations: [[nu_leptonsf]]
    binning:
      - ["tr_ttbar_mass", [500, 620, 820, 1100, 1500, 2500]]
      #- ["tr_ttbar_pt",   [-1e9, 300, 1e9]]
    base_points:
      - coords: [-1.0]
        loader: tt2l
        removeweights: ["reweightLeptonSF"] 
        addweights: ["reweightLeptonSFDown"] 
      - coords: [ 0.0]
        loader: tt2l
        nominal: true
      - coords: [ 1.0]
        loader: tt2l
        removeweights: ["reweightLeptonSF"] 
        addweights: ["reweightLeptonSFUp"] 
    output: { filename: "icph_tt2l_LeptonSF.pkl" }
  
  - id: icph_tt2l_BTag_b
    type: icph
    region: SR_binned
    parameters: [nu_btag_b]
    combinations: [[nu_btag_b]]
    binning:
      - ["tr_ttbar_mass", [500, 620, 820, 1100, 1500, 2500]]
      #- ["tr_ttbar_pt",   [-1e9, 300, 1e9]]
    base_points:
      - coords: [-1.0]
        loader: tt2l
        removeweights: ["reweightBTagSF1a_SF"] 
        addweights: ["reweightBTagSF1a_SF_b_Down"] 
      - coords: [ 0.0]
        loader: tt2l
        nominal: true
      - coords: [ 1.0]
        loader: tt2l
        removeweights: ["reweightBTagSF1a_SF"] 
        addweights: ["reweightBTagSF1a_SF_b_Up"] 
    output: { filename: "icph_tt2l_BTag_b.pkl" }
  
  - id: icph_tt2l_BTag_l
    type: icph
    region: SR_binned
    parameters: [nu_btag_l]
    combinations: [[nu_btag_l]]
    binning:
      - ["tr_ttbar_mass", [500, 620, 820, 1100, 1500, 2500]]
      #- ["tr_ttbar_pt",   [-1e9, 300, 1e9]]
    base_points:
      - coords: [-1.0]
        loader: tt2l
        removeweights: ["reweightBTagSF1a_SF"] 
        addweights: ["reweightBTagSF1a_SF_l_Down"] 
      - coords: [ 0.0]
        loader: tt2l
        nominal: true
      - coords: [ 1.0]
        loader: tt2l
        removeweights: ["reweightBTagSF1a_SF"] 
        addweights: ["reweightBTagSF1a_SF_l_Up"] 
    output: { filename: "icph_tt2l_BTag_l.pkl" }

  - id: icph_tt2l_scales
    type: icph
    region: SR_binned
    parameters: [nu_mu_ren, nu_mu_fac]
    combinations: [[nu_mu_ren], [nu_mu_fac], [nu_mu_ren, nu_mu_ren], [nu_mu_ren, nu_mu_fac], [nu_mu_fac, nu_mu_fac]]
    binning:
      - ["tr_ttbar_mass", [500, 620, 820, 1100, 1500, 2500]]
      #- ["tr_ttbar_pt",   [-1e9, 300, 1e9]]
    base_points:
      - coords: [-1.0, -1.0]
        loader: tt2l
        addweights: ["scale_ren0p5_fac0p5"]
      - coords: [-1.0, 0]
        loader: tt2l
        addweights: ["scale_ren0p5_fac1p0"]
      - coords: [-1.0, 1.0]
        loader: tt2l
        addweights: ["scale_ren0p5_fac2p0"]
      - coords: [0, -1.0]
        loader: tt2l
        addweights: ["scale_ren1p0_fac0p5"]
      - coords: [0, 0]
        loader: tt2l
        addweights: ["scale_ren1p0_fac1p0"]
        nominal: true
      - coords: [0, 1.0]
        loader: tt2l
        addweights: ["scale_ren1p0_fac2p0"]
      - coords: [1.0, -1.0]
        loader: tt2l
        addweights: ["scale_ren2p0_fac0p5"]
      - coords: [1.0, 0]
        loader: tt2l
        addweights: ["scale_ren2p0_fac1p0"]
      - coords: [1.0, 1.0]
        loader: tt2l
        addweights: ["scale_ren2p0_fac2p0"]
    output: { filename: "icph_tt2l_scales.pkl" }

  - id: icph_tt2l_jesTotal
    type: icph
    region: SR_binned
    parameters: [nu_jes]
    combinations: [[nu_jes], [nu_jes, nu_jes]]
    binning:
      - ["tr_ttbar_mass", [500, 620, 820, 1100, 1500, 2500]]
      #- ["tr_ttbar_mass",   [-1e9, 1e9]]
    base_points:
    #  - coords: [-2.0]
    #    loader: tt2l_2p0_jesTotalDown
    #  - coords: [-1.5]
    #    loader: tt2l_1p5_jesTotalDown 
      - coords: [-1.0]
        loader: tt2l_1p0_jesTotalDown
    #  - coords: [-0.5]
    #    loader: tt2l_0p5_jesTotalDown
      - coords: [0]
        loader: tt2l_jesNominal
        nominal: true
    #  - coords: [0.5]
    #    loader: tt2l_0p5_jesTotalUp
      - coords: [1.0]
        loader: tt2l_1p0_jesTotalUp
    #  - coords: [1.5]
    #    loader: tt2l_1p5_jesTotalUp
    #  - coords: [2.0]
    #    loader: tt2l_2p0_jesTotalUp
    output: { filename: "icph_tt2l_jesTotal.pkl" }
