jobs:
  - id: bit_pod_tt2l
    type: bit
    region: SR
    process: tt2l                 # loader/view name from data.samples
    selection: null               # optional extra selection layered on top
    pdf:
      pdf_n: [1, 2, 4, 5, 10, 12]                  
      pdf_type: PODBasis
    model:
      n_trees: 200
      learning_rate: 0.2
      loss: MSE                   # or "CrossEntropy"
      learn_global_score: true
    runtime:
      training_plots: true        # keep if you want training plots
    output:
      filename: "BIT_pod_tt2l.pkl"
