python icph_training.py ../../configs/binned_merged.yaml --overwrite --job icph_tt2l_Trigger
python icph_training.py ../../configs/binned_merged.yaml --overwrite --job icph_tt2l_L1Prefire
python icph_training.py ../../configs/binned_merged.yaml --overwrite --job icph_tt2l_PU
python icph_training.py ../../configs/binned_merged.yaml --overwrite --job icph_tt2l_LeptonSF
python icph_training.py ../../configs/binned_merged.yaml --overwrite --job icph_tt2l_BTag_b
python icph_training.py ../../configs/binned_merged.yaml --overwrite --job icph_tt2l_BTag_l
python icph_training.py ../../configs/binned_merged.yaml --overwrite --job icph_tt2l_scales
python icph_training.py ../../configs/binned_merged.yaml --overwrite --job icph_tt2l_jesTotal

python icph_training.py ../../configs/binned_split.yaml --overwrite --job icph_tt2l_GG_Trigger
python icph_training.py ../../configs/binned_split.yaml --overwrite --job icph_tt2l_GG_L1Prefire
python icph_training.py ../../configs/binned_split.yaml --overwrite --job icph_tt2l_GG_PU
python icph_training.py ../../configs/binned_split.yaml --overwrite --job icph_tt2l_GG_LeptonSF
python icph_training.py ../../configs/binned_split.yaml --overwrite --job icph_tt2l_GG_BTag_b
python icph_training.py ../../configs/binned_split.yaml --overwrite --job icph_tt2l_GG_BTag_l
python icph_training.py ../../configs/binned_split.yaml --overwrite --job icph_tt2l_GG_scales
python icph_training.py ../../configs/binned_split.yaml --overwrite --job icph_tt2l_GG_jesTotal
python icph_training.py ../../configs/binned_split.yaml --overwrite --job icph_tt2l_QG_Trigger
python icph_training.py ../../configs/binned_split.yaml --overwrite --job icph_tt2l_QG_L1Prefire
python icph_training.py ../../configs/binned_split.yaml --overwrite --job icph_tt2l_QG_PU
python icph_training.py ../../configs/binned_split.yaml --overwrite --job icph_tt2l_QG_LeptonSF
python icph_training.py ../../configs/binned_split.yaml --overwrite --job icph_tt2l_QG_BTag_b
python icph_training.py ../../configs/binned_split.yaml --overwrite --job icph_tt2l_QG_BTag_l
python icph_training.py ../../configs/binned_split.yaml --overwrite --job icph_tt2l_QG_scales
python icph_training.py ../../configs/binned_split.yaml --overwrite --job icph_tt2l_QG_jesTotal
python icph_training.py ../../configs/binned_split.yaml --overwrite --job icph_tt2l_QQ_Trigger
python icph_training.py ../../configs/binned_split.yaml --overwrite --job icph_tt2l_QQ_L1Prefire
python icph_training.py ../../configs/binned_split.yaml --overwrite --job icph_tt2l_QQ_PU
python icph_training.py ../../configs/binned_split.yaml --overwrite --job icph_tt2l_QQ_LeptonSF
python icph_training.py ../../configs/binned_split.yaml --overwrite --job icph_tt2l_QQ_BTag_b
python icph_training.py ../../configs/binned_split.yaml --overwrite --job icph_tt2l_QQ_BTag_l
python icph_training.py ../../configs/binned_split.yaml --overwrite --job icph_tt2l_QQ_scales
python icph_training.py ../../configs/binned_split.yaml --overwrite --job icph_tt2l_QQ_jesTotal

