python  pdf_postfit.py ../../configs/unbinned/unbinned_2016.yaml  --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016_binned_2016_v1_rotate_fit.json --Q 1.65 --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016.json
python  pdf_postfit.py ../../configs/unbinned/unbinned_2016.yaml  --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016_binned_2016_v1_rotate_fit.json --Q 1.65 --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016.json
python  pdf_postfit.py ../../configs/unbinned/unbinned_2016APV.yaml  --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016APV_binned_2016APV_v1_rotate_fit.json --Q 1.65 --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV.json
python  pdf_postfit.py ../../configs/unbinned/unbinned_2016APV.yaml  --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016APV_binned_2016APV_v1_rotate_fit.json --Q 1.65 --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV.json
python  pdf_postfit.py ../../configs/unbinned/unbinned_2017.yaml  --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2017_binned_2017_v1_rotate_fit.json --Q 1.65 --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2017.json
python  pdf_postfit.py ../../configs/unbinned/unbinned_2017.yaml  --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2017_binned_2017_v1_rotate_fit.json --Q 1.65 --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2017.json
python  pdf_postfit.py ../../configs/unbinned/unbinned_2018.yaml  --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2018_binned_2018_v1_rotate_fit.json --Q 1.65 --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2018.json
python  pdf_postfit.py ../../configs/unbinned/unbinned_2018.yaml  --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2018_binned_2018_v1_rotate_fit.json --Q 1.65 --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2018.json

