#python pdf_postfit.py ../../configs/unbinned/unbinned_2016.yaml  --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016_unbinned_2016_v1_rotate_fit.json --Q 1.65 --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016.json  
#python pdf_postfit.py ../../configs/unbinned/unbinned_2016.yaml  --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016_binned_2016_v1_rotate_fit.json --Q 1.65 --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016.json  
#
#python pdf_postfit.py ../../configs/unbinned/unbinned_2016APV.yaml  --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016APV_unbinned_2016APV_v1_rotate_fit.json --Q 1.65 --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV.json  
#python pdf_postfit.py ../../configs/unbinned/unbinned_2016APV.yaml  --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016APV_binned_2016APV_v1_rotate_fit.json --Q 1.65 --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV.json  
#
#python pdf_postfit.py ../../configs/unbinned/unbinned_2017.yaml  --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2017_unbinned_2017_v1_rotate_fit.json --Q 1.65 --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2017.json  
#python pdf_postfit.py ../../configs/unbinned/unbinned_2017.yaml  --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2017_binned_2017_v1_rotate_fit.json --Q 1.65 --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2017.json  
#
#python pdf_postfit.py ../../configs/unbinned/unbinned_2018.yaml  --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2018_unbinned_2018_v1_rotate_fit.json --Q 1.65 --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2018.json  
#python pdf_postfit.py ../../configs/unbinned/unbinned_2018.yaml  --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2018_binned_2018_v1_rotate_fit.json --Q 1.65 --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2018.json  

#python pdf_postfit_decompose.py ../../configs/unbinned/unbinned_2016.yaml  --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016_unbinned_2016_v1_rotate_fit.json --Q 1.65 --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016.json  
#
#python pdf_postfit_decompose.py ../../configs/unbinned/unbinned_2016APV.yaml  --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016APV_unbinned_2016APV_v1_rotate_fit.json --Q 1.65 --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV.json  
#
#python pdf_postfit_decompose.py ../../configs/unbinned/unbinned_2017.yaml  --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2017_unbinned_2017_v1_rotate_fit.json --Q 1.65 --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2017.json  
#
#python pdf_postfit_decompose.py ../../configs/unbinned/unbinned_2018.yaml  --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2018_unbinned_2018_v1_rotate_fit.json --Q 1.65 --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2018.json 

 
#python  pdf_postfit_decompose.py ../../configs/unbinned/unbinned_2016.yaml     --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016_unbinned_2016_v2_rotate_fit.json --Q 1.65 --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_unbinned_2016_v2.json 
#python  pdf_postfit_decompose.py ../../configs/unbinned/unbinned_2016APV.yaml  --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016APV_unbinned_2016APV_v2_rotate_fit.json --Q 1.65 --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_unbinned_2016APV_v2.json 
#python  pdf_postfit_decompose.py ../../configs/unbinned/unbinned_2017.yaml     --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2017_unbinned_2017_v2_rotate_fit.json --Q 1.65 --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2017_unbinned_2017_v2.json 
#python  pdf_postfit_decompose.py ../../configs/unbinned/unbinned_2018.yaml     --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2018_unbinned_2018_v2_rotate_fit.json --Q 1.65 --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2018_unbinned_2018_v2.json 

python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016APV/unbinned_2016APV_2.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016APV_2_binned_2016APV_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_2_unbinned_2016APV_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016APV/unbinned_2016APV_3.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016APV_3_binned_2016APV_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_3_unbinned_2016APV_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016APV/unbinned_2016APV_4.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016APV_4_binned_2016APV_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_4_unbinned_2016APV_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016APV/unbinned_2016APV_5.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016APV_5_binned_2016APV_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_5_unbinned_2016APV_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016APV/unbinned_2016APV_6.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016APV_6_binned_2016APV_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_6_unbinned_2016APV_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016APV/unbinned_2016APV_7.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016APV_7_binned_2016APV_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_7_unbinned_2016APV_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016APV/unbinned_2016APV_8.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016APV_8_binned_2016APV_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_8_unbinned_2016APV_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016APV/unbinned_2016APV_9.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016APV_9_binned_2016APV_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_9_unbinned_2016APV_v5.json

python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016/unbinned_2016_2.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016_2_binned_2016_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_2_unbinned_2016_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016/unbinned_2016_3.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016_3_binned_2016_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_3_unbinned_2016_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016/unbinned_2016_4.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016_4_binned_2016_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_4_unbinned_2016_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016/unbinned_2016_5.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016_5_binned_2016_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_5_unbinned_2016_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016/unbinned_2016_6.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016_6_binned_2016_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_6_unbinned_2016_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016/unbinned_2016_7.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016_7_binned_2016_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_7_unbinned_2016_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016/unbinned_2016_8.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016_8_binned_2016_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_8_unbinned_2016_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016/unbinned_2016_9.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016_9_binned_2016_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_9_unbinned_2016_v5.json

python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016APV/unbinned_2016APV_2.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016APV_2_unbinned_2016APV_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_2_unbinned_2016APV_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016APV/unbinned_2016APV_3.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016APV_3_unbinned_2016APV_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_3_unbinned_2016APV_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016APV/unbinned_2016APV_4.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016APV_4_unbinned_2016APV_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_4_unbinned_2016APV_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016APV/unbinned_2016APV_5.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016APV_5_unbinned_2016APV_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_5_unbinned_2016APV_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016APV/unbinned_2016APV_6.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016APV_6_unbinned_2016APV_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_6_unbinned_2016APV_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016APV/unbinned_2016APV_7.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016APV_7_unbinned_2016APV_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_7_unbinned_2016APV_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016APV/unbinned_2016APV_8.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016APV_8_unbinned_2016APV_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_8_unbinned_2016APV_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016APV/unbinned_2016APV_9.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016APV_9_unbinned_2016APV_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_9_unbinned_2016APV_v5.json

python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016/unbinned_2016_2.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016_2_unbinned_2016_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_2_unbinned_2016_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016/unbinned_2016_3.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016_3_unbinned_2016_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_3_unbinned_2016_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016/unbinned_2016_4.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016_4_unbinned_2016_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_4_unbinned_2016_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016/unbinned_2016_5.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016_5_unbinned_2016_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_5_unbinned_2016_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016/unbinned_2016_6.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016_6_unbinned_2016_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_6_unbinned_2016_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016/unbinned_2016_7.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016_7_unbinned_2016_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_7_unbinned_2016_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016/unbinned_2016_8.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016_8_unbinned_2016_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_8_unbinned_2016_v5.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5/2016/unbinned_2016_9.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016_9_unbinned_2016_v5_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_9_unbinned_2016_v5.json

python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016APV/unbinned_2016APV_2.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016APV_2_binned_2016APV_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_2_unbinned_2016APV_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016APV/unbinned_2016APV_3.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016APV_3_binned_2016APV_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_3_unbinned_2016APV_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016APV/unbinned_2016APV_4.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016APV_4_binned_2016APV_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_4_unbinned_2016APV_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016APV/unbinned_2016APV_5.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016APV_5_binned_2016APV_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_5_unbinned_2016APV_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016APV/unbinned_2016APV_6.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016APV_6_binned_2016APV_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_6_unbinned_2016APV_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016APV/unbinned_2016APV_7.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016APV_7_binned_2016APV_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_7_unbinned_2016APV_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016APV/unbinned_2016APV_8.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016APV_8_binned_2016APV_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_8_unbinned_2016APV_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016APV/unbinned_2016APV_9.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016APV_9_binned_2016APV_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_9_unbinned_2016APV_v5_CMSJES.json

python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016/unbinned_2016_2.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016_2_binned_2016_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_2_unbinned_2016_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016/unbinned_2016_3.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016_3_binned_2016_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_3_unbinned_2016_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016/unbinned_2016_4.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016_4_binned_2016_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_4_unbinned_2016_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016/unbinned_2016_5.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016_5_binned_2016_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_5_unbinned_2016_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016/unbinned_2016_6.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016_6_binned_2016_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_6_unbinned_2016_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016/unbinned_2016_7.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016_7_binned_2016_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_7_unbinned_2016_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016/unbinned_2016_8.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016_8_binned_2016_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_8_unbinned_2016_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016/unbinned_2016_9.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/binned_2016_9_binned_2016_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_9_unbinned_2016_v5_CMSJES.json

python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016APV/unbinned_2016APV_2.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016APV_2_unbinned_2016APV_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_2_unbinned_2016APV_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016APV/unbinned_2016APV_3.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016APV_3_unbinned_2016APV_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_3_unbinned_2016APV_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016APV/unbinned_2016APV_4.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016APV_4_unbinned_2016APV_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_4_unbinned_2016APV_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016APV/unbinned_2016APV_5.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016APV_5_unbinned_2016APV_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_5_unbinned_2016APV_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016APV/unbinned_2016APV_6.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016APV_6_unbinned_2016APV_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_6_unbinned_2016APV_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016APV/unbinned_2016APV_7.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016APV_7_unbinned_2016APV_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_7_unbinned_2016APV_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016APV/unbinned_2016APV_8.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016APV_8_unbinned_2016APV_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_8_unbinned_2016APV_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016APV/unbinned_2016APV_9.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016APV_9_unbinned_2016APV_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016APV_9_unbinned_2016APV_v5_CMSJES.json

python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016/unbinned_2016_2.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016_2_unbinned_2016_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_2_unbinned_2016_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016/unbinned_2016_3.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016_3_unbinned_2016_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_3_unbinned_2016_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016/unbinned_2016_4.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016_4_unbinned_2016_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_4_unbinned_2016_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016/unbinned_2016_5.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016_5_unbinned_2016_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_5_unbinned_2016_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016/unbinned_2016_6.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016_6_unbinned_2016_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_6_unbinned_2016_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016/unbinned_2016_7.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016_7_unbinned_2016_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_7_unbinned_2016_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016/unbinned_2016_8.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016_8_unbinned_2016_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_8_unbinned_2016_v5_CMSJES.json
python pdf_postfit_decompose.py ../../configs/unbinned_v5_CMSJES/2016/unbinned_2016_9.yaml --postfit /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/unbinned_2016_9_unbinned_2016_v5_CMSJES_rotate_fit.json --rotate /scratch-cbe/users/robert.schoefbeck/SBIPDF/output/orthogonal_basis_unbinned_2016_9_unbinned_2016_v5_CMSJES.json
