python ic_training.py --overwrite --selection inclusive
python ic_training.py --overwrite --selection lowMT_VBFJet
python ic_training.py --overwrite --selection highMT_VBFJet
python ic_training.py --overwrite --selection lowMT_noVBFJet_ptH0to100
python ic_training.py --overwrite --selection lowMT_noVBFJet_ptH100to200
python ic_training.py --overwrite --selection lowMT_noVBFJet_ptH200
python ic_training.py --overwrite --selection highMT_noVBFJet_ptH0to100
python ic_training.py --overwrite --selection highMT_noVBFJet_ptH100to200
python ic_training.py --overwrite --selection highMT_noVBFJet_ptH200
